using System;
using System.Collections.Generic;
using System.Drawing;
using System.Drawing.Drawing2D;
using System.Drawing.Imaging;
using System.Windows.Forms;

namespace HalkUIEditor {
    public sealed class CanvasOptions {
        public bool Grid=true,Snap=true,Names=true,Outlines=true,Cells=true,Background=true,Rulers=true;
        public int GridX=16,GridY=16,Major=4; public float Aspect=1;
        public Color BackgroundColor=Color.FromArgb(20,23,27),GridColor=Color.FromArgb(110,149,165);
        public bool Checker=true,BoxMode=false; public string TextureState="e",ManualBackground;
    }
    public sealed class EditorCanvas : Control {
        public ThemePalette Palette=ThemeCatalog.Create("classic"); public Func<bool> EditingAllowed; public Workspace Workspace; public UiDocument Document; public CanvasOptions Options=new CanvasOptions();
        public string AtlasFile=""; public List<string> Selection=new List<string>();
        public event EventHandler SelectionChanged,EditCommitted,GeometryPreview;
        public event Action<string> StatusChanged,Failure;
        public float Zoom=1; public PointF Pan=new PointF(30,30);
        bool panning,dragging,space,moved,marquee; string dragAnchor; PointF marqueeStart,marqueeEnd; List<string> marqueeBefore=new List<string>();Point mouseStart;PointF worldStart,panStart;string before;
        int resizeHandle=-1;Dictionary<string,RectangleF> initial=new Dictionary<string,RectangleF>();
        ToolTip tooltip=new ToolTip();string hover="";
        public EditorCanvas(){SetStyle(ControlStyles.AllPaintingInWmPaint|ControlStyles.OptimizedDoubleBuffer|ControlStyles.UserPaint|ControlStyles.Selectable,true);TabStop=true;BackColor=Color.FromArgb(20,23,27);Dock=DockStyle.Fill;AllowDrop=true;}
        public void Bind(Workspace w,UiDocument d){Workspace=w;Document=d;AtlasFile=d==null?"":d.DefaultAtlasReference;Selection.Clear();Options.Aspect=d!=null&&!d.Atlas&&System.IO.Path.GetFileNameWithoutExtension(d.FilePath).EndsWith("_16",StringComparison.OrdinalIgnoreCase)?4f/3f:1;Fit();ChangedSelection();}
        public float Aspect {get{return Document!=null&&Document.Atlas?1:Options.Aspect;}}
        public PointF ToWorld(Point p){return new PointF((p.X-Pan.X)/(Zoom*Aspect),(p.Y-Pan.Y)/Zoom);}
        public PointF ToScreen(PointF p){return new PointF(p.X*Zoom*Aspect+Pan.X,p.Y*Zoom+Pan.Y);}
        public RectangleF ScreenRect(RectangleF r){var p=ToScreen(r.Location);return new RectangleF(p.X,p.Y,r.Width*Zoom*Aspect,r.Height*Zoom);}
        public UiNode Primary {get{return Document==null||Selection.Count==0?null:Document.Node(Selection[0]);}}
        public RectangleF Frame(){if(Document!=null&&Document.Atlas){try{var path=Workspace.ResolveFile(AtlasFile);var b=Workspace.Image(path);if(b!=null)return new RectangleF(0,0,b.Width,b.Height);}catch(Exception){}}return new RectangleF(0,0,1024,768);}
        public void Fit(){RectangleF r=Frame();FitRect(r);}
        public void FitSelection(){var n=Primary;if(n!=null)FitRect(UiLayout.Rect(Document,n));else Fit();}
        void FitRect(RectangleF r){if(ClientSize.Width<50||ClientSize.Height<50||r.Width<=0||r.Height<=0)return;Zoom=Math.Max(.04f,Math.Min(8,Math.Min((ClientSize.Width-60)/(r.Width*Aspect),(ClientSize.Height-60)/r.Height)));Pan=new PointF((ClientSize.Width-r.Width*Zoom*Aspect)/2-r.X*Zoom*Aspect,(ClientSize.Height-r.Height*Zoom)/2-r.Y*Zoom);Invalidate();Report("Масштаб: "+Math.Round(Zoom*100)+"%");}
        public void SetZoom(float zoom){ZoomAt(zoom,new Point(ClientSize.Width/2,ClientSize.Height/2));}
        void ZoomAt(float zoom,Point p){PointF w=ToWorld(p);Zoom=Math.Max(.04f,Math.Min(16,zoom));Pan=new PointF(p.X-w.X*Zoom*Aspect,p.Y-w.Y*Zoom);Invalidate();Report("Масштаб: "+Math.Round(Zoom*100)+"%");}
        public void SelectKey(string key,bool additive){if(!additive)Selection.Clear();if(key!=null&&!Selection.Contains(key))Selection.Add(key);if(Document!=null&&Document.Atlas&&Primary!=null){string page=Document.AtlasReference(Primary);if(page!="")AtlasFile=page;}ChangedSelection();}
        void ChangedSelection(){Invalidate();if(SelectionChanged!=null)SelectionChanged(this,EventArgs.Empty);}
        void Report(string text){if(StatusChanged!=null)StatusChanged(text);}
        bool CanEdit(){if(EditingAllowed==null||EditingAllowed())return true;Report("Сначала примените или отмените правку во вкладке XML.");return false;}
        void Error(Exception ex){if(Failure!=null)Failure(ex.Message);}
        protected override void OnPaint(PaintEventArgs e){base.OnPaint(e);try{Draw(e.Graphics,ClientRectangle,true);}catch(Exception ex){TextRenderer.DrawText(e.Graphics,"Ошибка просмотра: "+ex.Message,Font,new Rectangle(20,50,Math.Max(20,Width-40),100),Color.Salmon,TextFormatFlags.WordBreak);}}
        void Draw(Graphics g,Rectangle viewport,bool editing){
            g.Clear(Options.BackgroundColor);if(Document==null){TextRenderer.DrawText(g,"Откройте папку gamedata или UI XML\nCtrl+O — открыть XML     Ctrl+Shift+O — открыть проект",Font,new Rectangle(30,80,Math.Max(100,Width-60),100),Palette.Muted,TextFormatFlags.HorizontalCenter|TextFormatFlags.WordBreak);return;}
            g.SmoothingMode=SmoothingMode.None;g.InterpolationMode=Zoom>=1?InterpolationMode.NearestNeighbor:InterpolationMode.HighQualityBilinear;g.PixelOffsetMode=PixelOffsetMode.Half;
            RectangleF frame=ScreenRect(Frame());if(Options.Checker){using(var a=new SolidBrush(Palette.Light?Color.FromArgb(236,239,242):Palette.Panel))using(var b=new SolidBrush(Palette.Light?Color.White:Palette.Raised)){g.FillRectangle(a,frame);int tile=16;Rectangle clip=Rectangle.Intersect(Rectangle.Ceiling(frame),viewport);for(int y=clip.Top/tile*tile;y<clip.Bottom;y+=tile)for(int x=clip.Left/tile*tile;x<clip.Right;x+=tile)if(((x/tile+y/tile)&1)==0)g.FillRectangle(b,Rectangle.Intersect(new Rectangle(x,y,tile,tile),clip));}}
            if(Options.Background){if(Document.Atlas){string path=Workspace.ResolveFile(AtlasFile);DrawTexture(g,path,Frame(),Frame());}
                else if(!string.IsNullOrEmpty(Options.ManualBackground)){var image=Workspace.Image(Options.ManualBackground);DrawTexture(g,Options.ManualBackground,new RectangleF(0,0,image.Width,image.Height),Frame());}
                else foreach(var n in VisibleNodes()){string name=UiLayout.TextureName(Document,n,Options.TextureState);if(name=="")continue;try{var t=Workspace.ResolveState(name,Options.TextureState);if(t!=null)DrawNodeTexture(g,n,t);}catch(Exception){}}
            }
            if(Options.Grid)DrawGrid(g,viewport);
            using(var border=new Pen(Palette.Border,1))g.DrawRectangle(border,frame.X,frame.Y,frame.Width,frame.Height);
            foreach(var n in VisibleNodes()){
                RectangleF r=ScreenRect(UiLayout.Rect(Document,n));if(r.Right<0||r.Bottom<0||r.Left>viewport.Right||r.Top>viewport.Bottom)continue;
                bool selected=Selection.Contains(n.Key);Color color=NodeColor(n);if(Document.Locked.Contains(n.Key))color=Color.FromArgb(117,125,134);
                if(Options.Outlines||selected){using(var shadow=new Pen(Color.FromArgb(selected?200:100,Color.Black),selected?4:3))g.DrawRectangle(shadow,r.X,r.Y,r.Width,r.Height);if(Palette.Light&&n.Name.StartsWith("dragdrop_"))color=Color.FromArgb(241,192,107);using(var pen=new Pen(Color.FromArgb(selected?255:210,color),selected?2:1)){if(Document.Locked.Contains(n.Key))pen.DashStyle=DashStyle.Dot;g.DrawRectangle(pen,r.X,r.Y,r.Width,r.Height);}}
                if(Options.Cells&&n.Has("cell_width")&&n.Has("cell_height")){int cols=Math.Min(200,(int)n.Number("cols_num",1)),rows=Math.Min(200,(int)n.Number("rows_num",1));float cw=n.Number("cell_width",1)*Zoom*Aspect,ch=n.Number("cell_height",1)*Zoom;if(cw>3&&ch>3)using(var pen=new Pen(Color.FromArgb(105,color),1)){for(int c=1;c<cols;c++){float x=r.X+c*cw;if(x>=r.Right)break;g.DrawLine(pen,x,r.Top,x,r.Bottom);}for(int row=1;row<rows;row++){float y=r.Y+row*ch;if(y>=r.Bottom)break;g.DrawLine(pen,r.Left,y,r.Right,y);}}}
                if((Options.Names||selected)&&r.Width>26&&r.Height>12){string label=Document.Atlas?n.Get("id",n.Name):n.Name;string tx=UiLayout.TextureName(Document,n);if(selected&&!Document.Atlas&&tx!="")label+="  ·  "+tx;int labelWidth=(int)Math.Min(Math.Max(0,viewport.Right-r.Left-4),(selected?TextRenderer.MeasureText(label,Font).Width+12:Math.Max(60,r.Width)));Rectangle labelRect=new Rectangle((int)r.Left+2,(int)r.Top+2,labelWidth,17);using(var brush=new SolidBrush(Color.FromArgb(235,Palette.Input)))g.FillRectangle(brush,labelRect);TextRenderer.DrawText(g,label,Font,labelRect,selected?Palette.Accent:color,TextFormatFlags.EndEllipsis|TextFormatFlags.NoPrefix|TextFormatFlags.SingleLine);}
            }
            if(editing&&Selection.Count==1&&Primary!=null&&Primary.Geometry&&!Document.Locked.Contains(Primary.Key)){foreach(var r in Handles(ScreenRect(UiLayout.Rect(Document,Primary)))){g.FillRectangle(Brushes.White,r);g.DrawRectangle(Pens.Black,r.X,r.Y,r.Width,r.Height);}}
            if(marquee&&editing){var r=ScreenRect(MarqueeBounds());using(var br=new SolidBrush(Color.FromArgb(36,Palette.Accent)))g.FillRectangle(br,r);using(var pen=new Pen(Palette.Accent)){pen.DashStyle=DashStyle.Dash;g.DrawRectangle(pen,r.X,r.Y,r.Width,r.Height);}}
            if(Options.Rulers&&editing)DrawRulers(g,viewport);
        }
        List<UiNode> VisibleNodes(){var nodes=UiLayout.Visible(Document);if(Document.Atlas)nodes.RemoveAll(delegate(UiNode n){return Document.AtlasReference(n)!=AtlasFile;});return nodes;}
        void DrawNodeTexture(Graphics g,UiNode n,TextureRegion t){var tx=UiLayout.TextureNode(n,Options.TextureState);RectangleF source=t.Source;if(tx!=null){source.X+=tx.Number("x",0);source.Y+=tx.Number("y",0);source.Width=tx.Number("width",source.Width);source.Height=tx.Number("height",source.Height);}if(t.FilePath==null||source.Width<=0||source.Height<=0)return;var world=UiLayout.Rect(Document,n);var dest=ScreenRect(world);Bitmap image=Workspace.Image(t.FilePath);string mirror=tx==null?"":tx.Get("mirror","");PointF[] points=new[]{new PointF(dest.Left,dest.Top),new PointF(dest.Right,dest.Top),new PointF(dest.Left,dest.Bottom)};if(mirror=="h")points=new[]{new PointF(dest.Right,dest.Top),new PointF(dest.Left,dest.Top),new PointF(dest.Right,dest.Bottom)};if(mirror=="v")points=new[]{new PointF(dest.Left,dest.Bottom),new PointF(dest.Right,dest.Bottom),new PointF(dest.Left,dest.Top)};using(var attributes=TextureAttributes(tx))g.DrawImage(image,points,source,GraphicsUnit.Pixel,attributes);}
        public static ImageAttributes TextureAttributes(UiNode tx){var attributes=new ImageAttributes();var matrix=new ColorMatrix();matrix.Matrix00=Tint(tx,"r");matrix.Matrix11=Tint(tx,"g");matrix.Matrix22=Tint(tx,"b");matrix.Matrix33=Tint(tx,"a");attributes.SetColorMatrix(matrix);return attributes;}
        static float Tint(UiNode n,string name){return n==null?1:Math.Max(0,Math.Min(255,n.Number(name,255)))/255f;}
        bool SelectedAncestor(UiNode n){var p=UiLayout.Parent(Document,n);int guard=0;while(p!=null&&guard++<40){if(Selection.Contains(p.Key))return true;p=UiLayout.Parent(Document,p);}return false;}
        void DrawTexture(Graphics g,string path,RectangleF source,RectangleF world){if(path==null||source.Width<=0||source.Height<=0||world.Width<=0||world.Height<=0)return;Bitmap image=Workspace.Image(path);if(image==null)return;RectangleF dest=ScreenRect(world);g.DrawImage(image,dest,source,GraphicsUnit.Pixel);}
        Color NodeColor(UiNode n){if(n.Name.StartsWith("dragdrop_"))return Palette.Accent;if(n.Name=="texture")return Palette.Geometry;if(n.Name.Contains("progress"))return Color.FromArgb(151,206,151);if(n.Name.Contains("back"))return Color.FromArgb(123,163,210);return Palette.Light?Color.FromArgb(96,77,116):Color.FromArgb(172,167,202);}
        void DrawGrid(Graphics g,Rectangle viewport){float sx=Math.Max(1,Options.GridX),sy=Math.Max(1,Options.GridY);while(sx*Zoom*Aspect<7)sx*=2;while(sy*Zoom<7)sy*=2;PointF a=ToWorld(new Point(0,0)),b=ToWorld(new Point(viewport.Right,viewport.Bottom));int major=Math.Max(1,Options.Major);using(var minor=new Pen(Color.FromArgb(38,Options.GridColor)))using(var bold=new Pen(Color.FromArgb(85,Options.GridColor))){int i0=(int)Math.Floor(a.X/sx),i1=(int)Math.Ceiling(b.X/sx);for(int i=i0;i<=i1&&i-i0<2000;i++){float x=ToScreen(new PointF(i*sx,0)).X;g.DrawLine(i%major==0?bold:minor,x,0,x,viewport.Bottom);}int j0=(int)Math.Floor(a.Y/sy),j1=(int)Math.Ceiling(b.Y/sy);for(int j=j0;j<=j1&&j-j0<2000;j++){float y=ToScreen(new PointF(0,j*sy)).Y;g.DrawLine(j%major==0?bold:minor,0,y,viewport.Right,y);}}}
        void DrawRulers(Graphics g,Rectangle viewport){using(var brush=new SolidBrush(Color.FromArgb(245,Palette.Panel))){g.FillRectangle(brush,0,0,viewport.Width,20);g.FillRectangle(brush,0,20,28,viewport.Height);}float step=32;while(step*Zoom*Aspect<54)step*=2;PointF min=ToWorld(new Point(28,20)),max=ToWorld(new Point(viewport.Right,viewport.Bottom));using(var rulerFont=new Font(Font.FontFamily,7))using(var pen=new Pen(Palette.Border)){for(float x=(float)Math.Ceiling(min.X/step)*step;x<max.X;x+=step){float px=ToScreen(new PointF(x,0)).X;g.DrawLine(pen,px,15,px,20);TextRenderer.DrawText(g,UiDocument.Num(x),Font,new Point((int)px+3,2),Palette.Muted);}while(step*Zoom<40)step*=2;for(float y=(float)Math.Ceiling(min.Y/step)*step;y<max.Y;y+=step){float py=ToScreen(new PointF(0,y)).Y;g.DrawLine(pen,23,py,28,py);TextRenderer.DrawText(g,UiDocument.Num(y),rulerFont,new Rectangle(0,(int)py-8,25,16),Palette.Muted,TextFormatFlags.Right);}}}
        static RectangleF[] Handles(RectangleF r){float x=r.X,y=r.Y,w=r.Width,h=r.Height;PointF[] p={new PointF(x,y),new PointF(x+w/2,y),new PointF(x+w,y),new PointF(x+w,y+h/2),new PointF(x+w,y+h),new PointF(x+w/2,y+h),new PointF(x,y+h),new PointF(x,y+h/2)};var result=new RectangleF[8];for(int i=0;i<8;i++)result[i]=new RectangleF(p[i].X-4,p[i].Y-4,8,8);return result;}
        UiNode Hit(PointF p){if(Document==null)return null;var nodes=VisibleNodes();UiNode hit=null;float area=float.MaxValue;for(int i=nodes.Count-1;i>=0;i--){var n=nodes[i];var r=UiLayout.Rect(Document,n);if(!Document.Locked.Contains(n.Key)&&r.Contains(p)&&r.Width*r.Height<area){hit=n;area=r.Width*r.Height;}}return hit;}
        protected override void OnMouseWheel(MouseEventArgs e){base.OnMouseWheel(e);if(dragging||marquee)return;ZoomAt(Zoom*(e.Delta>0?1.15f:1/1.15f),e.Location);}
        protected override void OnMouseDown(MouseEventArgs e){base.OnMouseDown(e);Focus();if(e.Button==MouseButtons.Middle||space&&e.Button==MouseButtons.Left){panning=true;mouseStart=e.Location;panStart=Pan;Capture=true;Cursor=Cursors.Hand;return;}if(e.Button!=MouseButtons.Left||Document==null)return;
            if(Options.BoxMode){BeginMarquee(e);return;}resizeHandle=-1;var primary=Primary;if(Selection.Count==1&&primary!=null&&primary.Geometry&&!Document.Locked.Contains(primary.Key)){var handles=Handles(ScreenRect(UiLayout.Rect(Document,primary)));for(int i=0;i<8;i++)if(handles[i].Contains(e.Location)){resizeHandle=i;break;}}
            if(resizeHandle<0){var hit=Hit(ToWorld(e.Location));bool ctrl=(ModifierKeys&Keys.Control)!=0;if(hit==null){BeginMarquee(e);return;}if(ctrl){if(Selection.Contains(hit.Key))Selection.Remove(hit.Key);else Selection.Add(hit.Key);ChangedSelection();return;}if(!Selection.Contains(hit.Key)){Selection.Clear();Selection.Add(hit.Key);ChangedSelection();}}
            if(!CanEdit())return;before=Document.Text;mouseStart=e.Location;worldStart=ToWorld(e.Location);initial.Clear();dragAnchor=null;foreach(string key in Selection){var n=Document.Node(key);if(n!=null&&!Document.Locked.Contains(key)&&n.Geometry&&!SelectedAncestor(n)){initial[key]=n.LocalRect;if(dragAnchor==null)dragAnchor=key;}}dragging=initial.Count>0;moved=false;Capture=dragging;
        }
        protected override void OnMouseMove(MouseEventArgs e){base.OnMouseMove(e);if(marquee){marqueeEnd=ToWorld(e.Location);var area=MarqueeBounds();Selection.Clear();Selection.AddRange(marqueeBefore);foreach(var n in VisibleNodes())if(!Document.Locked.Contains(n.Key)&&area.Contains(UiLayout.Rect(Document,n))&&!Selection.Contains(n.Key))Selection.Add(n.Key);Invalidate();return;}if(panning){Pan=new PointF(panStart.X+e.X-mouseStart.X,panStart.Y+e.Y-mouseStart.Y);Invalidate();return;}PointF world=ToWorld(e.Location);
            if(dragging){if(!moved&&Math.Abs(e.X-mouseStart.X)+Math.Abs(e.Y-mouseStart.Y)<3)return;moved=true;float dx=world.X-worldStart.X,dy=world.Y-worldStart.Y;bool freezeX=false,freezeY=false;if((ModifierKeys&Keys.Shift)!=0&&resizeHandle<0){if(Math.Abs(dx)>Math.Abs(dy)){dy=0;freezeY=true;}else{dx=0;freezeX=true;}}
                bool snap=Options.Snap&&(ModifierKeys&Keys.Alt)==0;if(snap&&resizeHandle<0&&dragAnchor!=null){var origin=initial[dragAnchor];dx=freezeX?0:Snap(origin.X+dx,Options.GridX)-origin.X;dy=freezeY?0:Snap(origin.Y+dy,Options.GridY)-origin.Y;}var changes=new Dictionary<string,Dictionary<string,string>>();
                foreach(var pair in initial){RectangleF start=pair.Value,r=start;float nx=dx,ny=dy;
                    if(resizeHandle<0){r.X+=nx;r.Y+=ny;}
                    else r=ResizeRectangle(start,dx,dy,resizeHandle,snap,Options.GridX,Options.GridY);
                    var values=new Dictionary<string,string>();values["x"]=UiDocument.Num(r.X);values["y"]=UiDocument.Num(r.Y);if(resizeHandle>=0){values["width"]=UiDocument.Num(r.Width);values["height"]=UiDocument.Num(r.Height);}changes[pair.Key]=values;
                }
                try{Document.SetAttributes(changes);Invalidate();if(GeometryPreview!=null)GeometryPreview(this,EventArgs.Empty);}catch(Exception ex){Error(ex);CancelDrag();}return;
            }
            string status="X: "+UiDocument.Num(world.X)+"   Y: "+UiDocument.Num(world.Y)+"   Масштаб: "+Math.Round(Zoom*100)+"%";UiNode hovered=Hit(world);if(hovered!=null){string tex=UiLayout.TextureName(Document,hovered);status+="   <"+hovered.Name+">"+(tex==""?"":"   Текстура: "+tex);if(hover!=hovered.Key){hover=hovered.Key;tooltip.SetToolTip(this,"<"+hovered.Name+">\n"+hovered.Key+"\nТекстура: "+(tex==""?"—":tex)+"\nCtrl+клик: несколько элементов · Alt: без привязки");}}else if(hover!=""){hover="";tooltip.SetToolTip(this,"");}Report(status);
        }
        protected override void OnMouseUp(MouseEventArgs e){base.OnMouseUp(e);if(marquee){marquee=false;Capture=false;ChangedSelection();return;}if(panning){panning=false;Capture=false;Cursor=Cursors.Default;return;}if(dragging){dragging=false;Capture=false;if(moved){Document.Commit(before);if(EditCommitted!=null)EditCommitted(this,EventArgs.Empty);}Invalidate();}}
        void CancelDrag(){if(marquee){Selection.Clear();Selection.AddRange(marqueeBefore);marquee=false;ChangedSelection();}if(dragging&&before!=null)Document.SetText(before);dragging=false;panning=false;Capture=false;Invalidate();if(EditCommitted!=null)EditCommitted(this,EventArgs.Empty);}
        void BeginMarquee(MouseEventArgs e){marquee=true;marqueeStart=marqueeEnd=ToWorld(e.Location);marqueeBefore=(ModifierKeys&Keys.Control)!=0?new List<string>(Selection):new List<string>();Selection.Clear();Selection.AddRange(marqueeBefore);Capture=true;Invalidate();}
        RectangleF MarqueeBounds(){return RectangleF.FromLTRB(Math.Min(marqueeStart.X,marqueeEnd.X),Math.Min(marqueeStart.Y,marqueeEnd.Y),Math.Max(marqueeStart.X,marqueeEnd.X),Math.Max(marqueeStart.Y,marqueeEnd.Y));}
        public void SelectAll(){Selection.Clear();if(Document!=null)foreach(var n in VisibleNodes())if(!Document.Locked.Contains(n.Key))Selection.Add(n.Key);ChangedSelection();}
        public static RectangleF ResizeRectangle(RectangleF start,float dx,float dy,int handle,bool snap,int gx,int gy){float l=start.Left,t=start.Top,r=start.Right,b=start.Bottom;bool left=handle==0||handle==6||handle==7,top=handle==0||handle==1||handle==2,right=handle==2||handle==3||handle==4,bottom=handle==4||handle==5||handle==6;if(left)l=Math.Min(r-1,snap?Snap(l+dx,gx):l+dx);if(right)r=Math.Max(l+1,snap?Snap(r+dx,gx):r+dx);if(top)t=Math.Min(b-1,snap?Snap(t+dy,gy):t+dy);if(bottom)b=Math.Max(t+1,snap?Snap(b+dy,gy):b+dy);return RectangleF.FromLTRB(l,t,r,b);}
        protected override void OnMouseCaptureChanged(EventArgs e){base.OnMouseCaptureChanged(e);if(!Capture&&(dragging||marquee))CancelDrag();if(!Capture&&panning){panning=false;Cursor=Cursors.Default;}}
        static float Snap(float n,int step){return (float)Math.Round(n/Math.Max(1,step))*Math.Max(1,step);}
        public void MoveSelected(float dx,float dy){if(Document==null||!CanEdit())return;string old=Document.Text;var changes=new Dictionary<string,Dictionary<string,string>>();foreach(string key in Selection){var n=Document.Node(key);if(n==null||!n.Geometry||Document.Locked.Contains(key)||SelectedAncestor(n))continue;changes[key]=new Dictionary<string,string>{{"x",UiDocument.Num(n.Number("x",0)+dx)},{"y",UiDocument.Num(n.Number("y",0)+dy)}};}Document.SetAttributes(changes);Document.Commit(old);if(EditCommitted!=null)EditCommitted(this,EventArgs.Empty);Invalidate();}
        public void Align(string mode){if(Document==null||Selection.Count<2||!CanEdit())return;string beforeText=Document.Text;var changes=new Dictionary<string,Dictionary<string,string>>();RectangleF anchor=UiLayout.Rect(Document,Primary);
            foreach(string key in Selection){var n=Document.Node(key);if(n==null||!n.Geometry||Document.Locked.Contains(key)||SelectedAncestor(n))continue;var r=UiLayout.Rect(Document,n);float dx=mode=="left"?anchor.Left-r.Left:mode=="centerx"?anchor.Left+anchor.Width/2-r.Left-r.Width/2:0;float dy=mode=="top"?anchor.Top-r.Top:mode=="centery"?anchor.Top+anchor.Height/2-r.Top-r.Height/2:0;changes[key]=new Dictionary<string,string>{{"x",UiDocument.Num(n.Number("x",0)+dx)},{"y",UiDocument.Num(n.Number("y",0)+dy)}};}
            Document.SetAttributes(changes);Document.Commit(beforeText);if(EditCommitted!=null)EditCommitted(this,EventArgs.Empty);Invalidate();}
        public void Export(string path){RectangleF f=Frame();int width=(int)Math.Ceiling(f.Width*Aspect),height=(int)Math.Ceiling(f.Height);if(width>8192||height>8192)throw new InvalidOperationException("Слишком большой экспорт.");float z=Zoom;PointF pan=Pan;try{Zoom=1;Pan=PointF.Empty;using(var b=new Bitmap(width,height))using(var g=Graphics.FromImage(b)){Draw(g,new Rectangle(0,0,width,height),false);b.Save(path,ImageFormat.Png);}}finally{Zoom=z;Pan=pan;}}
        protected override bool IsInputKey(Keys keyData){if((keyData&Keys.KeyCode)==Keys.Left||(keyData&Keys.KeyCode)==Keys.Right||(keyData&Keys.KeyCode)==Keys.Up||(keyData&Keys.KeyCode)==Keys.Down)return true;return base.IsInputKey(keyData);}
        protected override void OnKeyDown(KeyEventArgs e){base.OnKeyDown(e);if(e.KeyCode==Keys.Space){space=true;e.Handled=true;}if(e.KeyCode==Keys.Escape){CancelDrag();e.Handled=true;}float step=e.Shift?10:1;if(e.KeyCode==Keys.Left){MoveSelected(-step,0);e.Handled=true;}if(e.KeyCode==Keys.Right){MoveSelected(step,0);e.Handled=true;}if(e.KeyCode==Keys.Up){MoveSelected(0,-step);e.Handled=true;}if(e.KeyCode==Keys.Down){MoveSelected(0,step);e.Handled=true;}if(e.KeyCode==Keys.F){FitSelection();e.Handled=true;}}
        protected override void OnKeyUp(KeyEventArgs e){base.OnKeyUp(e);if(e.KeyCode==Keys.Space)space=false;}
        protected override void OnLostFocus(EventArgs e){base.OnLostFocus(e);space=false;}
        protected override void Dispose(bool disposing){if(disposing)tooltip.Dispose();base.Dispose(disposing);}
    }
}
