using System;
using System.Collections.Generic;
using System.Drawing;
using System.Drawing.Drawing2D;
using System.Globalization;
using System.IO;
using System.Text;
using System.Windows.Forms;
using System.Xml;

namespace HalkUIEditor {
    sealed class FileEntry {public string Path,Label;public override string ToString(){return Label;}}
    sealed class KeyEntry {public string Key,Label;public override string ToString(){return Label;}}
    public sealed class TexturePreview : Control {
        public Workspace Workspace; public TextureRegion TextureRegion; public string Error;public bool Crop=true;public ThemePalette Palette=ThemeCatalog.Create("classic");
        public TexturePreview(){DoubleBuffered=true;Height=180;Dock=DockStyle.Fill;}
        protected override void OnPaint(PaintEventArgs e){base.OnPaint(e);var g=e.Graphics;g.Clear(Palette.Input);try{if(Workspace==null||TextureRegion==null||TextureRegion.FilePath==null){TextRenderer.DrawText(g,Error??"Выберите элемент с текстурой",Font,Rectangle.Inflate(ClientRectangle,-10,-10),Palette.Muted,TextFormatFlags.HorizontalCenter|TextFormatFlags.VerticalCenter|TextFormatFlags.WordBreak);return;}var b=Workspace.Image(TextureRegion.FilePath);RectangleF source=Crop?TextureRegion.Source:new RectangleF(0,0,b.Width,b.Height);if(source.Width<=0||source.Height<=0)return;float z=Math.Max(.001f,Math.Min((Width-24f)/source.Width,(Height-24f)/source.Height));var rect=new RectangleF((Width-source.Width*z)/2,(Height-source.Height*z)/2,source.Width*z,source.Height*z);using(var br=new SolidBrush(Palette.Panel))g.FillRectangle(br,rect);using(var br=new SolidBrush(Palette.Raised)){for(int y=(int)rect.Top;y<rect.Bottom;y+=12)for(int x=(int)rect.Left;x<rect.Right;x+=12)if(((x/12+y/12)&1)==0)g.FillRectangle(br,RectangleF.Intersect(rect,new RectangleF(x,y,12,12)));}g.InterpolationMode=z>=1?InterpolationMode.NearestNeighbor:InterpolationMode.HighQualityBicubic;g.PixelOffsetMode=PixelOffsetMode.Half;g.DrawImage(b,rect,source,GraphicsUnit.Pixel);if(!Crop){var r=TextureRegion.Source;using(var pen=new Pen(Palette.Accent,2))g.DrawRectangle(pen,rect.Left+r.X*z,rect.Top+r.Y*z,r.Width*z,r.Height*z);}using(var pen=new Pen(Palette.Border))g.DrawRectangle(pen,rect.X,rect.Y,rect.Width,rect.Height);}catch(Exception ex){TextRenderer.DrawText(g,ex.Message,Font,Rectangle.Inflate(ClientRectangle,-8,-8),Palette.Accent,TextFormatFlags.WordBreak);}}
    }
    public sealed partial class MainForm : Form {
        public EditorCanvas Canvas=new EditorCanvas(); public Workspace Workspace;public UiDocument Document;
        TreeView tree=new TreeView();ListBox files=new ListBox(),textures=new ListBox();TextBox fileSearch=new TextBox(),nodeSearch=new TextBox(),textureSearch=new TextBox();
        Label projectLabel=new Label(),selectionLabel=new Label(),coordsLabel=new Label(),pathLabel=new Label(),textureInfo=new Label();
        DataGridView properties=new DataGridView();TextBox textureName=new TextBox();TexturePreview preview=new TexturePreview();
        ComboBox parentChoice=new ComboBox();CheckBox hidden=new CheckBox(),locked=new CheckBox(),engine=new CheckBox();
        ThemeTabs leftTabs=new ThemeTabs(),centerTabs=new ThemeTabs();RichTextBox source=new RichTextBox();ToolStripStatusLabel status=new ToolStripStatusLabel(),documentStatus=new ToolStripStatusLabel();
        ToolStripComboBox aspect=new ToolStripComboBox();ToolStripTextBox gridX=new ToolStripTextBox(),gridY=new ToolStripTextBox();ToolStripDropDownButton pages=new ToolStripDropDownButton("Лист атласа");
        Dictionary<string,TreeNode> treeNodes=new Dictionary<string,TreeNode>();Dictionary<string,ToolStripButton> toggles=new Dictionary<string,ToolStripButton>();
        bool binding,sourceDirty,closingSmoke;string sourceBase="";ToolTip tips=new ToolTip();
        string settingsPath=Path.Combine(Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData),"XRayUIEditor"),"settings.xml");
        public MainForm(){Text="X-Ray UI Editor";Size=new Size(1440,900);MinimumSize=new Size(1040,720);StartPosition=FormStartPosition.CenterScreen;Font=new Font("Segoe UI",9.25f);BackColor=PanelColor;ForeColor=TextColor;KeyPreview=true;BuildUI();InitializeEnhancements();LoadSettings();
            Canvas.SelectionChanged+=delegate{ShowSelection();};Canvas.EditCommitted+=delegate{RefreshDocument(false);};Canvas.GeometryPreview+=delegate{UpdateCoordinates();};Canvas.StatusChanged+=delegate(string s){status.Text=s;};Canvas.Failure+=delegate(string s){ShowError(s);};
            tree.AfterSelect+=delegate(object sender,TreeViewEventArgs e){if(!binding&&Document!=null){Canvas.SelectKey((string)e.Node.Tag,false);}};
            files.DoubleClick+=delegate{OpenSelectedFile();};files.KeyDown+=delegate(object sender,KeyEventArgs e){if(e.KeyCode==Keys.Enter){OpenSelectedFile();e.Handled=true;}};
            textures.DoubleClick+=delegate{ApplyTextureFromList();};fileSearch.TextChanged+=delegate{FillFiles();};nodeSearch.TextChanged+=delegate{FillTree();};textureSearch.TextChanged+=delegate{FillTextures();};
            properties.CellEndEdit+=PropertyChanged;properties.DataError+=delegate(object sender,DataGridViewDataErrorEventArgs e){e.ThrowException=false;};
            source.TextChanged+=delegate{if(!binding){sourceDirty=source.Text!=sourceBase;UpdateTitle();}};
            parentChoice.SelectedIndexChanged+=delegate{if(binding||Document==null||Canvas.Primary==null)return;var entry=parentChoice.SelectedItem as KeyEntry;if(entry==null)return;string key=Canvas.Primary.Key;if(entry.Key=="@auto")Document.PreviewParents.Remove(key);else {var p=Document.Node(entry.Key);for(int i=0;p!=null&&i<80;i++,p=UiLayout.Parent(Document,p))if(p.Key==key){ShowError("Такой родитель создаёт цикл.");ShowSelection();return;}Document.PreviewParents[key]=entry.Key;}Canvas.Invalidate();UpdateCoordinates();};
            hidden.CheckedChanged+=delegate{TogglePreviewFlag(Document==null?null:Document.Hidden,hidden.Checked);};locked.CheckedChanged+=delegate{TogglePreviewFlag(Document==null?null:Document.Locked,locked.Checked);};
            engine.CheckedChanged+=delegate{if(binding||Document==null)return;Document.EngineParents=engine.Checked;Canvas.Invalidate();UpdateCoordinates();};
            FormClosing+=OnClosing;AllowDrop=true;DragEnter+=OnDragEnter;DragDrop+=OnDragDrop;Canvas.DragEnter+=OnDragEnter;Canvas.DragDrop+=OnDragDrop;
        }
        void BuildUI(){
            var menu=new MenuStrip{BackColor=PanelColor,ForeColor=TextColor,Renderer=new ToolStripProfessionalRenderer(new EditorColors())};
            var file=new ToolStripMenuItem("Файл");AddMenu(file,"Открыть XML…",Keys.Control|Keys.O,OpenXml);AddMenu(file,"Открыть папку проекта…",Keys.Control|Keys.Shift|Keys.O,OpenFolder);AddMenu(file,"Новый XML…",Keys.Control|Keys.N,NewDocument);file.DropDownItems.Add(new ToolStripSeparator());AddMenu(file,"Сохранить",Keys.Control|Keys.S,delegate{Save(false);});AddMenu(file,"Сохранить как…",Keys.Control|Keys.Shift|Keys.S,delegate{Save(true);});AddMenu(file,"Сохранить все изменённые XML",Keys.None,SaveAll);AddMenu(file,"Экспортировать просмотр в PNG…",Keys.None,ExportImage);file.DropDownItems.Add(new ToolStripSeparator());AddMenu(file,"Сохранить настройки проекта…",Keys.None,SaveProject);AddMenu(file,"Загрузить настройки проекта…",Keys.None,LoadProject);AddMenu(file,"Выход",Keys.Alt|Keys.F4,Close);
            var edit=new ToolStripMenuItem("Правка");AddMenu(edit,"Отменить",Keys.Control|Keys.Z,Undo);AddMenu(edit,"Повторить",Keys.Control|Keys.Y,Redo);AddMenu(edit,"Дублировать элемент",Keys.Control|Keys.D,Duplicate);AddMenu(edit,"Удалить выбранное",Keys.None,Delete);AddMenu(edit,"Добавить элемент…",Keys.None,AddNode);AddMenu(edit,"Применить текст XML",Keys.Control|Keys.Enter,delegate{ApplySource();});
            var view=new ToolStripMenuItem("Вид");AddMenu(view,"Вписать весь экран",Keys.Control|Keys.D0,Canvas.Fit);AddMenu(view,"Вписать выделение",Keys.None,Canvas.FitSelection);AddMenu(view,"Масштаб 100%",Keys.Control|Keys.D1,delegate{Canvas.SetZoom(1);});AddMenu(view,"Свой фон DDS / PNG…",Keys.None,ChooseBackground);AddMenu(view,"Вернуть фон из XML",Keys.None,delegate{Canvas.Options.ManualBackground=null;Canvas.Invalidate();});AddMenu(view,"Папка текстур вручную…",Keys.None,ChooseTexturesFolder);AddMenu(view,"Цвет фона…",Keys.None,delegate{ChooseColor(false);});AddMenu(view,"Цвет сетки…",Keys.None,delegate{ChooseColor(true);});AddMenu(view,"Частота основных линий сетки…",Keys.None,SetMajorGrid);
            var toolsMenu=new ToolStripMenuItem("Инструменты");AddMenu(toolsMenu,"Проверить текущий XML",Keys.F7,ValidateDocument);AddMenu(toolsMenu,"Обновить каталог текстур",Keys.None,delegate{if(Workspace!=null){ReloadTextures();RefreshDocument(false);}});AddMenu(toolsMenu,"Выровнять слева",Keys.None,delegate{Canvas.Align("left");});AddMenu(toolsMenu,"Выровнять сверху",Keys.None,delegate{Canvas.Align("top");});AddMenu(toolsMenu,"Центры по горизонтали",Keys.None,delegate{Canvas.Align("centerx");});AddMenu(toolsMenu,"Центры по вертикали",Keys.None,delegate{Canvas.Align("centery");});
            var help=new ToolStripMenuItem("Помощь");AddMenu(help,"Управление и ограничения",Keys.F1,ShowHelp);menu.Items.AddRange(new ToolStripItem[]{file,edit,view,toolsMenu,help});MainMenuStrip=menu;
            var toolbar=Strip();Button(toolbar,"Открыть проект",OpenFolder);Button(toolbar,"XML…",OpenXml);toolbar.Items.Add(new ToolStripSeparator());Button(toolbar,"Сохранить",delegate{Save(false);});Button(toolbar,"↶ Отмена",Undo);Button(toolbar,"↷",Redo);toolbar.Items.Add(new ToolStripSeparator());Button(toolbar,"Вписать",Canvas.Fit);Button(toolbar,"100%",delegate{Canvas.SetZoom(1);});toolbar.Items.Add(new ToolStripLabel("Экран:"));aspect.DropDownStyle=ComboBoxStyle.DropDownList;aspect.Items.AddRange(new object[]{"4:3 · 1024×768","16:9 · 1024×768","16:10 · 1024×768"});aspect.Width=160;aspect.SelectedIndex=0;aspect.SelectedIndexChanged+=delegate{Canvas.Options.Aspect=aspect.SelectedIndex==1?4f/3f:aspect.SelectedIndex==2?1.2f:1;Canvas.Fit();};toolbar.Items.Add(aspect);toolbar.Items.Add(pages);
            var guides=Strip();Toggle(guides,"Сетка","grid",true,delegate(bool v){Canvas.Options.Grid=v;});guides.Items.Add(new ToolStripLabel("X"));gridX.Text="16";gridX.AutoSize=false;gridX.Width=40;guides.Items.Add(gridX);guides.Items.Add(new ToolStripLabel("Y"));gridY.Text="16";gridY.AutoSize=false;gridY.Width=40;guides.Items.Add(gridY);gridX.Leave+=GridStepChanged;gridY.Leave+=GridStepChanged;gridX.KeyDown+=GridKey;gridY.KeyDown+=GridKey;
            Toggle(guides,"Привязка","snap",true,delegate(bool v){Canvas.Options.Snap=v;});Toggle(guides,"Линейки","rulers",true,delegate(bool v){Canvas.Options.Rulers=v;});guides.Items.Add(new ToolStripSeparator());Toggle(guides,"Рамкой","box",false,delegate(bool v){Canvas.Options.BoxMode=v;});Toggle(guides,"Текстуры","background",true,delegate(bool v){Canvas.Options.Background=v;});Toggle(guides,"Рамки","outlines",true,delegate(bool v){Canvas.Options.Outlines=v;});Toggle(guides,"Имена","names",false,delegate(bool v){Canvas.Options.Names=v;});Canvas.Options.Names=false;Toggle(guides,"Ячейки","cells",true,delegate(bool v){Canvas.Options.Cells=v;});Toggle(guides,"Альфа-фон","checker",true,delegate(bool v){Canvas.Options.Checker=v;});
            var layout=CreateWorkspaceSplit();
            leftTabs.Dock=DockStyle.Fill;var project=new TabPage("Файлы");var elements=new TabPage("Элементы");var textureTab=new TabPage("Текстуры");leftTabs.TabPages.AddRange(new[]{project,elements,textureTab});StylePage(project);StylePage(elements);StylePage(textureTab);
            projectLabel.Text="ПРОЕКТ НЕ ОТКРЫТ";projectLabel.Dock=DockStyle.Top;projectLabel.Height=54;projectLabel.Padding=new Padding(8);projectLabel.ForeColor=Accent;projectLabel.AutoEllipsis=true;
            StyleList(files);files.Dock=DockStyle.Fill;project.Controls.Add(files);var openFile=SmallButton("Открыть выбранный XML",OpenSelectedFile);openFile.Dock=DockStyle.Bottom;project.Controls.Add(openFile);project.Controls.Add(SearchBar(fileSearch,"Поиск XML"));project.Controls.Add(projectLabel);
            tree.Dock=DockStyle.Fill;tree.BackColor=InputColor;tree.ForeColor=TextColor;tree.BorderStyle=BorderStyle.None;tree.HideSelection=false;tree.FullRowSelect=true;tree.ItemHeight=23;tree.ShowNodeToolTips=true;elements.Controls.Add(tree);elements.Controls.Add(SearchBar(nodeSearch,"Имя элемента или текстуры"));
            StyleList(textures);textures.Dock=DockStyle.Fill;textureTab.Controls.Add(textures);var applyTexture=SmallButton("Назначить выбранную текстуру",ApplyTextureFromList);applyTexture.Dock=DockStyle.Bottom;textureTab.Controls.Add(applyTexture);textureTab.Controls.Add(SearchBar(textureSearch,"Поиск texture id"));
            centerTabs.Dock=DockStyle.Fill;var design=new TabPage("Развёрстка");var xmlPage=new TabPage("XML");StylePage(design);StylePage(xmlPage);design.Controls.Add(Canvas);source.Dock=DockStyle.Fill;source.Font=new Font("Consolas",10);source.BackColor=InputColor;source.ForeColor=TextColor;source.AcceptsTab=true;source.WordWrap=false;source.DetectUrls=false;source.BorderStyle=BorderStyle.None;xmlPage.Controls.Add(source);var apply=SmallButton("Применить XML  ·  Ctrl+Enter",delegate{ApplySource();});apply.Dock=DockStyle.Top;xmlPage.Controls.Add(apply);centerTabs.TabPages.AddRange(new[]{design,xmlPage});
            AttachWorkspacePanels(layout,BuildInspector());
            var footer=new StatusStrip{BackColor=PanelColor,ForeColor=TextColor};status.Spring=true;status.TextAlign=ContentAlignment.MiddleLeft;status.Text="Откройте папку с XML и текстурами";documentStatus.ForeColor=Accent;footer.Items.Add(status);footer.Items.Add(documentStatus);
            Controls.Add(layout);Controls.Add(guides);Controls.Add(toolbar);Controls.Add(menu);Controls.Add(footer);
        }
        Control BuildInspector(){return CreateInspectorTabs();}
        void AddRow(TableLayoutPanel p,Control c,int h){int i=p.RowCount++;p.RowStyles.Add(new RowStyle(SizeType.Absolute,h));c.Dock=DockStyle.Fill;c.Margin=new Padding(0,1,0,2);p.Controls.Add(c,0,i);}
        Label LabelFor(string s){return new Label{Text=s,Tag="muted",ForeColor=Color.FromArgb(163,174,188),TextAlign=ContentAlignment.MiddleLeft};}
        Control SearchBar(TextBox box,string hint){var p=new Panel{Dock=DockStyle.Top,Height=49,Padding=new Padding(6,0,6,5)};var l=new Label{Text=hint,Dock=DockStyle.Top,Height=19,ForeColor=Color.FromArgb(166,177,189)};StyleInput(box);box.Dock=DockStyle.Bottom;p.Controls.Add(box);p.Controls.Add(l);return p;}
        void StylePage(TabPage p){p.BackColor=PanelColor;p.ForeColor=TextColor;p.Padding=new Padding(0);}
        void StyleInput(Control c){c.BackColor=InputColor;c.ForeColor=TextColor;var t=c as TextBox;if(t!=null)t.BorderStyle=BorderStyle.FixedSingle;}
        void StyleList(ListBox c){c.BackColor=InputColor;c.ForeColor=TextColor;c.BorderStyle=BorderStyle.None;c.HorizontalScrollbar=true;c.IntegralHeight=false;c.ItemHeight=21;}
        Button SmallButton(string text,Action action){var b=new Button{Text=text,AutoSize=true,Height=29,FlatStyle=FlatStyle.Flat,BackColor=Color.FromArgb(52,58,67),ForeColor=TextColor,Padding=new Padding(4,0,4,0),Margin=new Padding(0,1,4,1)};b.FlatAppearance.BorderColor=Color.FromArgb(69,77,88);b.Click+=delegate{Guard(action);};return b;}
        ToolStrip Strip(){return new ToolStrip{Dock=DockStyle.Top,GripStyle=ToolStripGripStyle.Hidden,BackColor=PanelColor,ForeColor=TextColor,Padding=new Padding(7,3,0,3),Renderer=new ToolStripProfessionalRenderer(new EditorColors())};}
        void Button(ToolStrip strip,string text,Action action){var b=new ToolStripButton(text){Padding=new Padding(5,3,5,3)};b.Click+=delegate{Guard(action);};strip.Items.Add(b);}
        void Toggle(ToolStrip strip,string text,string key,bool value,Action<bool> action){var b=new ToolStripButton(text){CheckOnClick=true,Checked=value,Padding=new Padding(4,3,4,3)};b.CheckedChanged+=delegate{action(b.Checked);Canvas.Invalidate();};toggles[key]=b;strip.Items.Add(b);}
        void AddMenu(ToolStripMenuItem parent,string text,Keys shortcut,Action action){var item=new ToolStripMenuItem(text){ShortcutKeys=shortcut};item.Click+=delegate{Guard(action);};parent.DropDownItems.Add(item);}
        public void Guard(Action action){try{action();}catch(Exception ex){ShowError(ex.Message);}}
        void ShowError(string text){status.Text=text;MessageBox.Show(this,text,"X-Ray UI Editor",MessageBoxButtons.OK,MessageBoxIcon.Warning);}
        void GridKey(object sender,KeyEventArgs e){if(e.KeyCode==Keys.Enter){GridStepChanged(sender,EventArgs.Empty);Canvas.Focus();e.Handled=true;}}
        void GridStepChanged(object sender,EventArgs e){int x,y;if(!int.TryParse(gridX.Text,out x)||x<1||x>1024||!int.TryParse(gridY.Text,out y)||y<1||y>1024){gridX.Text=Canvas.Options.GridX.ToString();gridY.Text=Canvas.Options.GridY.ToString();status.Text="Шаг сетки: целое число от 1 до 1024";return;}Canvas.Options.GridX=x;Canvas.Options.GridY=y;Canvas.Invalidate();}
        void SetMajorGrid(){string s=Prompt.Ask(this,"Основные линии","Каждая N-я линия (1–64):",Canvas.Options.Major.ToString());int v;if(s!=null&&int.TryParse(s,out v)&&v>=1&&v<=64){Canvas.Options.Major=v;Canvas.Invalidate();}}
        void ChooseColor(bool grid){using(var d=new ColorDialog{Color=grid?Canvas.Options.GridColor:Canvas.Options.BackgroundColor})if(d.ShowDialog(this)==DialogResult.OK){if(grid)Canvas.Options.GridColor=d.Color;else Canvas.Options.BackgroundColor=d.Color;Canvas.Invalidate();}}
        void OpenFolder(){using(var d=new FolderBrowserDialog{Description="Выберите папку с config(s), XML и textures. Для архива примеров — папку, где лежат config и textures."})if(d.ShowDialog(this)==DialogResult.OK)OpenWorkspace(d.SelectedPath,null);}
        void OpenXml(){using(var d=new OpenFileDialog{Filter="UI XML|*.xml|Все файлы|*.*"})if(d.ShowDialog(this)==DialogResult.OK){if(Workspace!=null&&d.FileName.StartsWith(Workspace.Root+Path.DirectorySeparatorChar,StringComparison.OrdinalIgnoreCase))OpenDocument(d.FileName);else OpenWorkspace(Workspace.FindRoot(d.FileName),d.FileName);}}
        public bool OpenWorkspace(string root,string file){return OpenWorkspace(root,file,false);}
        bool OpenWorkspace(string root,string file,bool leaveConfirmed){if(!leaveConfirmed&&!CanLeaveWorkspace())return false;UseWaitCursor=true;try{var next=new Workspace(root);if(Workspace!=null)Workspace.Dispose();Workspace=next;Document=null;Canvas.Bind(next,null);sourceDirty=false;sourceBase="";FillFiles();projectLabel.Text=Path.GetFileName(root)+"\n"+Workspace.Files.Count+" XML · "+Workspace.ImageFiles.Count+" текстур";tips.SetToolTip(projectLabel,root);if(file==null){foreach(string p in Workspace.Files)if(Path.GetFileName(p).Equals("inventory_new.xml",StringComparison.OrdinalIgnoreCase)){file=p;break;}}if(file==null&&Workspace.Files.Count>0)file=Workspace.Files[0];if(file!=null)OpenDocument(file);else{FillTextures();FillTree();ShowSelection();}status.Text="Проект открыт. Двойной щелчок по XML для выбора.";return true;}finally{UseWaitCursor=false;}}
        void OpenSelectedFile(){var f=files.SelectedItem as FileEntry;if(f!=null)OpenDocument(f.Path);}
        public void OpenDocument(string path){if(!EnsureSource())return;var next=Workspace.Open(path);Document=next;Workspace.Activate(next);Canvas.Bind(Workspace,next);binding=true;source.Text=Document.Text;sourceBase=Document.Text;sourceDirty=false;binding=false;aspect.SelectedIndex=Path.GetFileNameWithoutExtension(path).EndsWith("_16",StringComparison.OrdinalIgnoreCase)?1:0;RefreshDocument(true);leftTabs.SelectedIndex=1;centerTabs.SelectedIndex=Document.ParseError==null?0:1;Canvas.Focus();Canvas.Fit();if(Document.ParseError!=null){status.Text=Document.ParseError;MessageBox.Show(this,"XML открыт для исправления во вкладке кода.\n\n"+Document.ParseError,"Ошибка исходного XML",MessageBoxButtons.OK,MessageBoxIcon.Warning);}}
        void FillFiles(){if(Workspace==null)return;files.BeginUpdate();files.Items.Clear();string q=fileSearch.Text.Trim();foreach(var p in Workspace.Files){string label=p.Substring(Workspace.Root.Length).TrimStart(Path.DirectorySeparatorChar);if(q!=""&&label.IndexOf(q,StringComparison.OrdinalIgnoreCase)<0)continue;UiDocument d;bool dirty=Workspace.Documents.TryGetValue(p,out d)&&d.Dirty;files.Items.Add(new FileEntry{Path=p,Label=(dirty?"* ":"")+label});}files.EndUpdate();}
        void FillTextures(){textures.BeginUpdate();textures.Items.Clear();if(Workspace!=null){var ids=new List<string>(Workspace.Textures.Keys);ids.Sort(StringComparer.OrdinalIgnoreCase);foreach(string id in ids)if(id.IndexOf(textureSearch.Text.Trim(),StringComparison.OrdinalIgnoreCase)>=0)textures.Items.Add(id);}textures.EndUpdate();}
        void FillTree(){binding=true;tree.BeginUpdate();tree.Nodes.Clear();treeNodes.Clear();if(Document!=null){string q=nodeSearch.Text.Trim();TreeNode root=BuildTree(Document.Xml.Root,q);if(root!=null){tree.Nodes.Add(root);root.Expand();if(Document.Xml.Nodes.Count<90)root.ExpandAll();}if(Canvas.Primary!=null){TreeNode n;if(treeNodes.TryGetValue(Canvas.Primary.Key,out n)){tree.SelectedNode=n;n.EnsureVisible();}}}tree.EndUpdate();binding=false;}
        TreeNode BuildTree(UiNode n,string q){string tx=UiLayout.TextureName(Document,n);string label=n.Name=="texture"&&n.Has("id")?n.Get("id",n.Name):n.Name;var result=new TreeNode(label){Tag=n.Key,ToolTipText=n.Key+(tx==""?"":"\nТекстура: "+tx)};foreach(var c in n.Children){var child=BuildTree(c,q);if(child!=null)result.Nodes.Add(child);}bool hit=q==""||label.IndexOf(q,StringComparison.OrdinalIgnoreCase)>=0||tx.IndexOf(q,StringComparison.OrdinalIgnoreCase)>=0;if(!hit&&result.Nodes.Count==0)return null;if(Document.Hidden.Contains(n.Key))result.ForeColor=Color.Gray;else if(n.Name.StartsWith("dragdrop_"))result.ForeColor=Accent;else if(n.Geometry)result.ForeColor=Color.FromArgb(150,206,203);treeNodes[n.Key]=result;return result;}
        void RefreshDocument(bool full){if(Document==null)return;Canvas.Selection.RemoveAll(delegate(string key){return Document.Node(key)==null;});if(Document.Atlas){Workspace.Reindex();Canvas.AtlasFile=Canvas.Primary==null?Document.DefaultAtlasReference:Document.AtlasReference(Canvas.Primary);if(Canvas.AtlasFile=="")Canvas.AtlasFile=Document.DefaultAtlasReference;}if(!sourceDirty){binding=true;int pos=source.SelectionStart;source.Text=Document.Text;sourceBase=Document.Text;source.Select(Math.Min(pos,source.TextLength),0);binding=false;}if(full){FillFiles();FillTextures();}FillTree();FillPages();ShowSelection();Canvas.Invalidate();UpdateTitle();}
        void FillPages(){pages.DropDownItems.Clear();pages.Visible=Document!=null&&Document.Atlas;if(!pages.Visible)return;var refs=new HashSet<string>();foreach(var n in Document.Xml.Nodes){string name=Document.AtlasReference(n);if(name==""||!refs.Add(name))continue;string copy=name;var item=new ToolStripMenuItem(name){Checked=name==Canvas.AtlasFile};item.Click+=delegate{Canvas.AtlasFile=copy;Canvas.Selection.Clear();Canvas.Fit();FillPages();ShowSelection();};pages.DropDownItems.Add(item);}}
        void ShowSelection(){binding=true;var n=Canvas.Primary;properties.Rows.Clear();parentChoice.Items.Clear();preview.Workspace=Workspace;preview.TextureRegion=null;preview.Error=null;textureInfo.Text="";selectionLabel.Text=n==null?"СВОЙСТВА ЭЛЕМЕНТА":n.Get("id",n.Name);pathLabel.Text=n==null?"Выберите элемент на холсте или в дереве.":n.Key;textureName.Text=n==null?"":UiLayout.TextureName(Document,n);hidden.Checked=n!=null&&Document.Hidden.Contains(n.Key);locked.Checked=n!=null&&Document.Locked.Contains(n.Key);engine.Checked=Document==null||Document.EngineParents;
            if(n!=null){foreach(var a in n.Attributes)properties.Rows.Add(a.Name,a.Value);if(n.Geometry)foreach(string a in new[]{"x","y","width","height"})if(!n.Has(a))properties.Rows.Add(a,n.Get(a,"0"));TreeNode tn;if(treeNodes.TryGetValue(n.Key,out tn)){tree.SelectedNode=tn;tn.EnsureVisible();}parentChoice.Items.Add(new KeyEntry{Key="@auto",Label="Автоматически"});parentChoice.Items.Add(new KeyEntry{Key="@origin",Label="Начало экрана (0, 0)"});foreach(var candidate in Document.Xml.Nodes)if(candidate!=n&&candidate.Geometry&&!candidate.Key.StartsWith(n.Key+"/",StringComparison.Ordinal))parentChoice.Items.Add(new KeyEntry{Key=candidate.Key,Label=candidate.Key});string chosen;Document.PreviewParents.TryGetValue(n.Key,out chosen);parentChoice.SelectedIndex=0;for(int i=0;i<parentChoice.Items.Count;i++)if(((KeyEntry)parentChoice.Items[i]).Key==chosen)parentChoice.SelectedIndex=i;
                try{TextureRegion t;if(Document.Atlas)t=new TextureRegion{Id=n.Get("id",n.Name),FileReference=textureName.Text,FilePath=Workspace.ResolveFile(textureName.Text),Source=n.LocalRect,OwnerFile=Document.FilePath,NodeKey=n.Key};else t=Workspace.ResolveState(UiLayout.TextureName(Document,n,Canvas.Options.TextureState),Canvas.Options.TextureState);preview.TextureRegion=t;if(t!=null){textureInfo.Text=(t.FilePath==null?"Файл не найден: "+t.FileReference:Path.GetFileName(t.FilePath))+"\nUV: "+UiDocument.Num(t.Source.X)+", "+UiDocument.Num(t.Source.Y)+" · "+UiDocument.Num(t.Source.Width)+" × "+UiDocument.Num(t.Source.Height);tips.SetToolTip(textureInfo,(t.FilePath??t.FileReference)+"\n"+t.OwnerFile);}else if(textureName.Text!="")preview.Error="Текстура не найдена в выбранном варианте UI";}catch(Exception ex){preview.Error=ex.Message;}}
            selectedTextureLabel.Text=textureName.Text==""?"Текстура не назначена":"↗  "+textureName.Text;tips.SetToolTip(selectedTextureLabel,textureName.Text);UpdateCoordinates();UpdateGeometryInputs();binding=false;preview.Invalidate();}
        void UpdateCoordinates(){var n=Canvas.Primary;if(n==null){coordsLabel.Text="";return;}var r=UiLayout.Rect(Document,n);coordsLabel.Text="X "+n.Get("x","0")+"    Y "+n.Get("y","0")+"    W "+n.Get("width","0")+"    H "+n.Get("height","0")+"\nНа экране: "+UiDocument.Num(r.X)+", "+UiDocument.Num(r.Y)+(Canvas.Selection.Count>1?" · выделено "+Canvas.Selection.Count:"");}
        void UpdateTitle(){Text=(Document==null?"":(Document.Dirty||sourceDirty?"* ":"")+Path.GetFileName(Document.FilePath)+" — ")+"X-Ray UI Editor 1.1";UpdateWorkspaceHeading();documentStatus.Text=Document==null?"":(Document.Atlas?"АТЛАС":"РАЗВЁРСТКА")+" · "+Document.Encoding.WebName+" · "+(Workspace.ActiveVariant==""?"общий набор":Workspace.ActiveVariant)+(Document.Dirty||sourceDirty?" · изменён":"");}
        void Change(Action action){if(Document==null||!EnsureSource())return;string before=Document.Text;try{action();Document.Commit(before);RefreshDocument(false);}catch{if(Document.Text!=before)Document.SetText(before);throw;}}
        void PropertyChanged(object sender,DataGridViewCellEventArgs e){if(binding||e.RowIndex<0||e.ColumnIndex!=1||Canvas.Primary==null)return;string name=Convert.ToString(properties.Rows[e.RowIndex].Cells[0].Value),value=Convert.ToString(properties.Rows[e.RowIndex].Cells[1].Value),key=Canvas.Primary.Key;Guard(delegate{if(name=="x"||name=="y"||name=="width"||name=="height"||name=="cell_width"||name=="cell_height"){float f;if(!float.TryParse(value.Replace(',','.'),NumberStyles.Float,CultureInfo.InvariantCulture,out f)||float.IsNaN(f)||float.IsInfinity(f))throw new FormatException("Нужно конечное число.");if(name!="x"&&name!="y"&&f<0)throw new FormatException("Размер не может быть отрицательным.");value=UiDocument.Num(f);}Change(delegate{Document.SetAttribute(key,name,value);});});ShowSelection();}
        void AddAttribute(){var n=Canvas.Primary;if(n==null)return;string name=Prompt.Ask(this,"Новый атрибут","Имя атрибута:","stretch");if(name==null)return;string value=Prompt.Ask(this,"Значение","Значение "+name+":","1");if(value!=null)Change(delegate{Document.SetAttribute(n.Key,name,value);});}
        void RemoveAttribute(){if(Canvas.Primary==null||properties.CurrentRow==null)return;string name=Convert.ToString(properties.CurrentRow.Cells[0].Value),key=Canvas.Primary.Key;Change(delegate{Document.RemoveAttribute(key,name);});}
        void ApplyTextureText(){var n=Canvas.Primary;if(n!=null){string name=textureName.Text.Trim();Change(delegate{Document.SetTexture(n.Key,name);});}}
        void ApplyTextureFromList(){if(textures.SelectedItem==null||Canvas.Primary==null||Document.Atlas){status.Text="Выберите элемент развёрстки, затем texture id.";return;}string name=textures.SelectedItem.ToString(),key=Canvas.Primary.Key;Change(delegate{Document.SetTexture(key,name);});}
        void JumpAtlas(){if(Document==null||Document.Atlas||Canvas.Primary==null)return;var t=Workspace.ResolveState(UiLayout.TextureName(Document,Canvas.Primary,Canvas.Options.TextureState),Canvas.Options.TextureState);if(t==null||t.OwnerFile==null){status.Text="У этой текстуры нет XML-дескриптора; её можно назначить своим фоном.";return;}OpenDocument(t.OwnerFile);Canvas.SelectKey(t.NodeKey,false);Canvas.Fit();}
        void SyncGrid(){var n=Canvas.Primary;if(n==null||!n.Has("cell_width")||!n.Has("cell_height")){status.Text="Выберите dragdrop с параметрами ячеек.";return;}Change(delegate{var v=new Dictionary<string,string>{{"width",UiDocument.Num(n.Number("cell_width",1)*n.Number("cols_num",1))},{"height",UiDocument.Num(n.Number("cell_height",1)*n.Number("rows_num",1))}};var d=new Dictionary<string,Dictionary<string,string>>();d[n.Key]=v;Document.SetAttributes(d);});}
        void TogglePreviewFlag(HashSet<string> set,bool enabled){if(binding||set==null||Canvas.Primary==null)return;foreach(string key in Canvas.Selection){if(enabled)set.Add(key);else set.Remove(key);}FillTree();Canvas.Invalidate();}
        void Undo(){if(centerTabs.SelectedIndex==1&&sourceDirty){source.Undo();return;}if(Document!=null&&Document.Undo())RefreshDocument(false);}
        void Redo(){if(centerTabs.SelectedIndex==1&&sourceDirty){source.Redo();return;}if(Document!=null&&Document.Redo())RefreshDocument(false);}
        void Duplicate(){var n=Canvas.Primary;if(n==null)return;string key=n.Key;Change(delegate{key=Document.Duplicate(key);});Canvas.SelectKey(key,false);}
        void Delete(){if(Document==null||Canvas.Selection.Count==0)return;var keys=new List<string>(Canvas.Selection);Change(delegate{Document.DeleteNodes(keys);});Canvas.Selection.Clear();RefreshDocument(false);}
        void AddNode(){if(Document==null)return;string name=Prompt.Ask(this,"Добавить элемент","Имя тега:",Document.Atlas?"texture":"auto_static");if(name==null)return;if(!System.Text.RegularExpressions.Regex.IsMatch(name,@"^[A-Za-z_][\w:.-]*$"))throw new FormatException("Некорректное имя тега.");var parent=Canvas.Primary??Document.Xml.Root;if(parent.SelfClosing||parent.Name=="texture")parent=parent.Parent??Document.Xml.Root;int pos=parent.CloseStart;string id=Document.Atlas?" id=\"new_texture_"+Guid.NewGuid().ToString("N").Substring(0,6)+"\"":"";string block="\n    <"+name+id+" x=\"0\" y=\"0\" width=\"64\" height=\"64\"/>\n";Change(delegate{Document.SetText(Document.Text.Insert(pos,block));});}
        bool ApplySource(){if(Document==null||!sourceDirty)return true;if(Document.Text!=sourceBase){ShowError("Развёрстка изменилась после начала правки XML. Скопируйте свой текст, затем отмените его правку и объедините изменения вручную.");return false;}string old=Document.Text;try{Document.SetText(source.Text);Document.Bytes();Document.Commit(old);sourceBase=Document.Text;sourceDirty=false;Workspace.Reindex();RefreshDocument(true);return true;}catch(Exception ex){if(Document.Text!=old)Document.SetText(old);ShowError(ex.Message);return false;}}
        bool EnsureSource(){if(!sourceDirty)return true;var r=MessageBox.Show(this,"Во вкладке XML есть неприменённые изменения. Применить их?\n«Нет» — вернуть текст текущей развёрстки.","Изменения XML",MessageBoxButtons.YesNoCancel,MessageBoxIcon.Question);if(r==DialogResult.Cancel)return false;if(r==DialogResult.Yes)return ApplySource();binding=true;source.Text=Document.Text;sourceBase=Document.Text;sourceDirty=false;binding=false;return true;}
        void ShowInSource(){if(Canvas.Primary==null||!EnsureSource())return;centerTabs.SelectedIndex=1;source.Focus();source.Select(Canvas.Primary.Start,Canvas.Primary.OpenEnd-Canvas.Primary.Start);source.ScrollToCaret();}
        bool Save(bool saveAs){if(Document==null||!EnsureSource())return false;string path=Document.FilePath;if(saveAs){using(var d=new SaveFileDialog{Filter="UI XML|*.xml",FileName=Path.GetFileName(path),InitialDirectory=Path.GetDirectoryName(path)}){if(d.ShowDialog(this)!=DialogResult.OK)return false;path=d.FileName;}}string oldPath=Document.FilePath;string backup=Document.Save(path);if(!string.Equals(oldPath,path,StringComparison.OrdinalIgnoreCase)){Workspace.Documents.Remove(oldPath);Workspace.Documents[path]=Document;if(!Workspace.Files.Contains(path))Workspace.Files.Add(path);Workspace.Activate(Document);}RefreshDocument(true);status.Text=backup==""?"Сохранено: "+Path.GetFileName(path):"Сохранено. Резервная копия: "+Path.GetFileName(backup);return true;}
        void SaveAll(){if(Workspace==null||!EnsureSource())return;int count=0;foreach(var d in Workspace.Documents.Values)if(d.Dirty){d.Save(d.FilePath);count++;}RefreshDocument(true);status.Text="Сохранено XML: "+count;}
        bool CanLeaveWorkspace(){if(!EnsureSource())return false;if(Workspace==null)return true;int count=0;foreach(var d in Workspace.Documents.Values)if(d.Dirty)count++;if(count==0)return true;var r=MessageBox.Show(this,"Сохранить изменённые XML ("+count+")?","Закрытие проекта",MessageBoxButtons.YesNoCancel,MessageBoxIcon.Question);if(r==DialogResult.Cancel)return false;if(r==DialogResult.Yes){try{SaveAll();}catch(Exception ex){ShowError(ex.Message);return false;}}return true;}
        void NewDocument(){using(var d=new SaveFileDialog{Filter="UI XML|*.xml",FileName="new_ui.xml"}){if(d.ShowDialog(this)!=DialogResult.OK)return;if(!CanLeaveWorkspace())return;string text="<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<window>\n    <main x=\"0\" y=\"0\" width=\"1024\" height=\"768\"/>\n    <auto_static x=\"64\" y=\"64\" width=\"256\" height=\"128\"/>\n</window>\n";if(File.Exists(d.FileName))throw new IOException("Для нового XML выберите несуществующее имя, чтобы сохранить существующий файл.");File.WriteAllText(d.FileName,text,new UTF8Encoding(false));OpenWorkspace(Workspace.FindRoot(d.FileName),d.FileName,true);}}
        void ChooseBackground(){using(var d=new OpenFileDialog{Filter="Текстуры|*.dds;*.png;*.bmp;*.jpg;*.jpeg"})if(d.ShowDialog(this)==DialogResult.OK){if(Workspace==null)OpenWorkspace(Path.GetDirectoryName(d.FileName),null);if(Workspace==null)return;Workspace.Image(d.FileName);Canvas.Options.ManualBackground=d.FileName;Canvas.Options.Background=true;toggles["background"].Checked=true;Canvas.Invalidate();}}
        void ChooseTexturesFolder(){if(Workspace==null)return;using(var d=new FolderBrowserDialog{Description="Папка textures или папка с DDS текущего варианта"})if(d.ShowDialog(this)==DialogResult.OK){Workspace.TextureDirectory=d.SelectedPath;Workspace.Reindex();FillTextures();ShowSelection();Canvas.Invalidate();}}
        void ExportImage(){if(Document==null)return;using(var d=new SaveFileDialog{Filter="PNG|*.png",FileName=Path.GetFileNameWithoutExtension(Document.FilePath)+"_preview.png"})if(d.ShowDialog(this)==DialogResult.OK){Canvas.Export(d.FileName);status.Text="Просмотр экспортирован в PNG.";}}
        void ValidateDocument(){if(Document==null||!EnsureSource())return;UseWaitCursor=true;try{var warnings=UiLayout.Validate(Document,Workspace);warnings.AddRange(Workspace.Warnings);ShowReport("Проверка XML",warnings.Count==0?"Проверка завершена: ошибок координат и подключений не найдено.":string.Join(Environment.NewLine,warnings.ToArray()));}finally{UseWaitCursor=false;}}
        void ShowReport(string title,string text){using(var f=new Form{Text=title,Size=new Size(820,540),StartPosition=FormStartPosition.CenterParent,Font=Font}){var t=new TextBox{Dock=DockStyle.Fill,Multiline=true,ReadOnly=true,ScrollBars=ScrollBars.Both,WordWrap=false,Text=text,BackColor=InputColor,ForeColor=TextColor};f.Controls.Add(t);ThemeCatalog.Apply(f,currentTheme);f.ShowDialog(this);}}
        void ShowHelp(){ShowReport("Управление", "Откройте папку, содержащую config(s) и textures. Архив сначала распакуйте.\r\nСлева: файлы, дерево элементов и список texture id. Двойной щелчок открывает XML.\r\n\r\nКолесо — масштаб под указателем. Средняя кнопка или пробел + мышь — панорама.\r\nПеретаскивание — позиция. Белые маркеры — размер. Ctrl + клик — несколько элементов.\r\nСтрелки — 1 единица, Shift + стрелки — 10. Alt во время перетаскивания отключает привязку.\r\nF — вписать выделение. Esc — отменить текущее перетаскивание.\r\nCtrl+S — сохранить; Ctrl+Z / Ctrl+Y — история; Ctrl+D — дубликат.\r\n\r\nСетка, привязка, имена, текстуры, рамки, ячейки и линейки включаются независимо.\r\n«Рамкой» — групповое выделение. F5 перечитывает DDS; F11 скрывает боковые панели.\r\nСемь тем — в меню «Тема» справа. Выбранная тема запоминается.\r\nКоординаты XML остаются в системе 1024×768. Режим 16:9 меняет только пропорции просмотра.\r\n\r\nВ режиме АТЛАС правятся UV-области texture id, в режиме РАЗВЁРСТКА — координаты окон.\r\nФайлы DDS не перезаписываются. Их цвет и пиксели здесь не редактируются.\r\nОригинальные комментарии, #include и кодировка XML сохраняются. При записи создаётся .bak.\r\n\r\nПросмотр не запускает движок игры: скрипты, динамический текст и анимация не исполняются;\r\n#include сохраняется как текст и не раскрывается. Шрифты INI/SEQ можно подключать в игре,\r\nно редактор не редактирует их. Составные рамки движка и разные состояния кнопок\r\nмогут выглядеть иначе; используется обычная текстура / состояние _e.\r\nДля нестандартного UI задайте родителя просмотра вручную.\r\nНастройки проекта (.halk.xml) сохраняют родителей, скрытие и блокировку отдельно от игровых XML.\r\n\r\nПоддержаны DDS DXT1/3/5, A8, RGB16/24/32, DX10 BC1/2/3 и RGBA/BGRA8.\r\nДля запуска используется системный .NET Framework. В программе нет сетевых запросов.");}
        void OnDragEnter(object sender,DragEventArgs e){e.Effect=e.Data.GetDataPresent(DataFormats.FileDrop)?DragDropEffects.Copy:DragDropEffects.None;}
        void OnDragDrop(object sender,DragEventArgs e){string[] items=e.Data.GetData(DataFormats.FileDrop) as string[];if(items==null||items.Length==0)return;Guard(delegate{string p=items[0];if(Directory.Exists(p))OpenWorkspace(p,null);else if(Path.GetExtension(p).Equals(".xml",StringComparison.OrdinalIgnoreCase))OpenWorkspace(Workspace.FindRoot(p),p);else status.Text="Перетащите распакованную папку проекта или XML.";});}
        void OnClosing(object sender,FormClosingEventArgs e){if(closingSmoke)return;if(!CanLeaveWorkspace()){e.Cancel=true;return;}SaveSettings();if(Workspace!=null)Workspace.Dispose();}
        public void SmokeOutput(string path){closingSmoke=true;string directory=Path.GetDirectoryName(Path.GetFullPath(path));Directory.CreateDirectory(directory);string checks=SelfTest.ExerciseUI(this);File.WriteAllText(Path.Combine(directory,"ui-check.txt"),checks);Canvas.Fit();if(Document!=null)foreach(var n in Document.Xml.Nodes)if(n.Name.StartsWith("dragdrop_")){Canvas.SelectKey(n.Key,false);break;}SetTheme("classic",false);CapturePreview(path);foreach(string id in ThemeCatalog.Ids){SetTheme(id,false);CapturePreview(Path.Combine(directory,"theme-"+id+".png"));}SetTheme("soc",false);inspectorTabs.SelectedIndex=1;CapturePreview(Path.Combine(directory,"texture-preview.png"));SetTheme("classic",false);Canvas.Export(Path.Combine(directory,"canvas.png"));Close();}
        void CapturePreview(string path){Refresh();Application.DoEvents();using(var b=new Bitmap(Width,Height)){DrawToBitmap(b,new Rectangle(0,0,Width,Height));b.Save(path,System.Drawing.Imaging.ImageFormat.Png);}}
        void LoadSettings(){try{if(!File.Exists(settingsPath))return;var x=new XmlDocument();x.XmlResolver=null;x.Load(settingsPath);ReadView(x.DocumentElement);}catch(Exception){}}
        void SaveSettings(){try{Directory.CreateDirectory(Path.GetDirectoryName(settingsPath));var x=new XmlDocument();var root=x.CreateElement("view");x.AppendChild(root);WriteView(root);x.Save(settingsPath);}catch(Exception){}}
        void WriteView(XmlElement e){SaveThemeSettings(e);e.SetAttribute("grid_x",Canvas.Options.GridX.ToString());e.SetAttribute("grid_y",Canvas.Options.GridY.ToString());e.SetAttribute("major",Canvas.Options.Major.ToString());e.SetAttribute("grid_color",Canvas.Options.GridColor.ToArgb().ToString());e.SetAttribute("background_color",Canvas.Options.BackgroundColor.ToArgb().ToString());foreach(var v in toggles)e.SetAttribute(v.Key,v.Value.Checked?"1":"0");}
        void ReadView(XmlElement e){LoadThemeSettings(e);int v;if(int.TryParse(e.GetAttribute("grid_x"),out v)&&v>=1&&v<=1024)Canvas.Options.GridX=v;if(int.TryParse(e.GetAttribute("grid_y"),out v)&&v>=1&&v<=1024)Canvas.Options.GridY=v;if(int.TryParse(e.GetAttribute("major"),out v)&&v>=1&&v<=64)Canvas.Options.Major=v;if(int.TryParse(e.GetAttribute("grid_color"),out v))Canvas.Options.GridColor=Color.FromArgb(v);if(int.TryParse(e.GetAttribute("background_color"),out v))Canvas.Options.BackgroundColor=Color.FromArgb(v);gridX.Text=Canvas.Options.GridX.ToString();gridY.Text=Canvas.Options.GridY.ToString();foreach(var t in toggles)if(e.HasAttribute(t.Key))t.Value.Checked=e.GetAttribute(t.Key)=="1";}
        string Relative(string path){return path.StartsWith(Workspace.Root+Path.DirectorySeparatorChar,StringComparison.OrdinalIgnoreCase)?path.Substring(Workspace.Root.Length+1):path;}
        void SaveProject(){if(Workspace==null)return;using(var dialog=new SaveFileDialog{Filter="Настройки проекта|*.halk.xml",FileName="ui_project.halk.xml",InitialDirectory=Workspace.Root})if(dialog.ShowDialog(this)==DialogResult.OK){var x=new XmlDocument();var r=x.CreateElement("ui_editor_project");x.AppendChild(r);r.SetAttribute("root",Workspace.Root);r.SetAttribute("texture_directory",Workspace.TextureDirectory??"");r.SetAttribute("active",Document==null?"":Relative(Document.FilePath));r.SetAttribute("background",Canvas.Options.ManualBackground??"");WriteView(r);foreach(var d in Workspace.Documents.Values){if(d.Hidden.Count==0&&d.Locked.Count==0&&d.PreviewParents.Count==0&&d.EngineParents)continue;var doc=x.CreateElement("document");doc.SetAttribute("file",Relative(d.FilePath));doc.SetAttribute("engine_parents",d.EngineParents?"1":"0");r.AppendChild(doc);foreach(var n in d.Xml.Nodes){if(!d.Hidden.Contains(n.Key)&&!d.Locked.Contains(n.Key)&&!d.PreviewParents.ContainsKey(n.Key))continue;var el=x.CreateElement("node");el.SetAttribute("key",n.Key);if(d.Hidden.Contains(n.Key))el.SetAttribute("hidden","1");if(d.Locked.Contains(n.Key))el.SetAttribute("locked","1");string parent;if(d.PreviewParents.TryGetValue(n.Key,out parent))el.SetAttribute("parent",parent);doc.AppendChild(el);}}x.Save(dialog.FileName);status.Text="Настройки проекта сохранены.";}}
        void LoadProject(){using(var dialog=new OpenFileDialog{Filter="Настройки проекта|*.halk.xml"})if(dialog.ShowDialog(this)==DialogResult.OK){var x=new XmlDocument();x.XmlResolver=null;x.Load(dialog.FileName);var r=x.DocumentElement;if(r.Name!="ui_editor_project")throw new FormatException("Это не файл настроек редактора.");string root=r.GetAttribute("root");if(!Directory.Exists(root))root=Path.GetDirectoryName(dialog.FileName);if(!OpenWorkspace(root,null))return;if(Workspace==null||!string.Equals(Workspace.Root,root,StringComparison.OrdinalIgnoreCase))return;Workspace.TextureDirectory=r.GetAttribute("texture_directory");Canvas.Options.ManualBackground=r.GetAttribute("background");ReadView(r);foreach(XmlElement el in r.SelectNodes("document")){string path=Path.Combine(root,el.GetAttribute("file"));if(!File.Exists(path))continue;var d=Workspace.Open(path);d.EngineParents=el.GetAttribute("engine_parents")!="0";d.Hidden.Clear();d.Locked.Clear();d.PreviewParents.Clear();foreach(XmlElement n in el.SelectNodes("node")){string key=n.GetAttribute("key");if(d.Node(key)==null)continue;if(n.GetAttribute("hidden")=="1")d.Hidden.Add(key);if(n.GetAttribute("locked")=="1")d.Locked.Add(key);if(n.HasAttribute("parent"))d.PreviewParents[key]=n.GetAttribute("parent");}}Workspace.Reindex();string active=r.GetAttribute("active");if(active!=""&&File.Exists(Path.Combine(root,active)))OpenDocument(Path.Combine(root,active));else RefreshDocument(true);}}
    }
    sealed class EditorColors : ProfessionalColorTable {
        public override Color ToolStripGradientBegin{get{return Color.FromArgb(38,42,49);}}public override Color ToolStripGradientMiddle{get{return ToolStripGradientBegin;}}public override Color ToolStripGradientEnd{get{return ToolStripGradientBegin;}}public override Color MenuStripGradientBegin{get{return ToolStripGradientBegin;}}public override Color MenuStripGradientEnd{get{return ToolStripGradientBegin;}}public override Color ButtonCheckedGradientBegin{get{return Color.FromArgb(98,83,56);}}public override Color ButtonCheckedGradientMiddle{get{return ButtonCheckedGradientBegin;}}public override Color ButtonCheckedGradientEnd{get{return ButtonCheckedGradientBegin;}}public override Color ButtonSelectedGradientBegin{get{return Color.FromArgb(72,81,94);}}public override Color ButtonSelectedGradientMiddle{get{return ButtonSelectedGradientBegin;}}public override Color ButtonSelectedGradientEnd{get{return ButtonSelectedGradientBegin;}}public override Color ToolStripDropDownBackground{get{return Color.FromArgb(51,57,67);}}public override Color ImageMarginGradientBegin{get{return ToolStripDropDownBackground;}}public override Color ImageMarginGradientMiddle{get{return ToolStripDropDownBackground;}}public override Color ImageMarginGradientEnd{get{return ToolStripDropDownBackground;}}
    }
    static class Prompt {
        public static string Ask(IWin32Window owner,string title,string label,string value){using(var f=new Form{Text=title,Width=450,Height=175,StartPosition=FormStartPosition.CenterParent,FormBorderStyle=FormBorderStyle.FixedDialog,MinimizeBox=false,MaximizeBox=false,Font=new Font("Segoe UI",9)}){var l=new Label{Left=14,Top=13,Width=405,Text=label};var t=new TextBox{Left=14,Top=39,Width=405,Text=value};var ok=new Button{Left=240,Top=78,Width=85,Text="Применить",DialogResult=DialogResult.OK};var cancel=new Button{Left=334,Top=78,Width=85,Text="Отмена",DialogResult=DialogResult.Cancel};f.Controls.AddRange(new Control[]{l,t,ok,cancel});f.AcceptButton=ok;f.CancelButton=cancel;var editor=owner as MainForm;if(editor!=null)ThemeCatalog.Apply(f,editor.ActivePalette);return f.ShowDialog(owner)==DialogResult.OK?t.Text:null;}}
    }
}
