using System;using System.Collections.Generic;using System.Drawing;using System.Drawing.Imaging;using System.IO;using System.Text;using System.Security.Cryptography;
namespace HalkUIEditor {
    public static class SelfTest {
        static void Check(bool value,string message){if(!value)throw new Exception(message);}
        static bool Equal(byte[] a,byte[] b){if(a.Length!=b.Length)return false;for(int i=0;i<a.Length;i++)if(a[i]!=b[i])return false;return true;}
        static void U(byte[] b,int p,uint v){for(int i=0;i<4;i++)b[p+i]=(byte)(v>>(8*i));}
        static byte[] Dds(string type){int payload=type=="DXT1"?8:type=="A8"?16:16;var b=new byte[128+payload];U(b,0,0x20534444);U(b,4,124);U(b,8,0x1007);U(b,12,4);U(b,16,4);U(b,76,32);U(b,108,0x1000);if(type=="A8"){U(b,80,2);U(b,88,8);U(b,104,255);for(int i=0;i<16;i++)b[128+i]=(byte)(i*17);}else{U(b,80,4);U(b,84,(uint)(type[0]|type[1]<<8|type[2]<<16|type[3]<<24));int c=type=="DXT1"?128:136;b[c]=0;b[c+1]=248;if(type=="DXT3")for(int i=0;i<8;i++)b[128+i]=0x88;if(type=="DXT5"){b[128]=200;b[129]=100;}}return b;}
        static void Write(string path,string text){Directory.CreateDirectory(Path.GetDirectoryName(path));File.WriteAllText(path,text,new UTF8Encoding(false));}
        public static string MakeExample(string folder){Directory.CreateDirectory(folder);string tex=Path.Combine(folder,"textures/ui");Directory.CreateDirectory(tex);using(var image=new Bitmap(1024,1024))using(var g=Graphics.FromImage(image)){g.Clear(Color.Transparent);using(var background=new System.Drawing.Drawing2D.LinearGradientBrush(new Rectangle(0,0,720,768),Color.FromArgb(45,51,57),Color.FromArgb(22,27,33),90)){g.FillRectangle(background,0,0,720,768);}using(var p=new Pen(Color.FromArgb(132,125,102),2)){g.DrawRectangle(p,8,8,704,750);g.DrawRectangle(p,27,78,220,420);g.DrawRectangle(p,266,78,426,580);}using(var f=new Font("Arial",20,FontStyle.Bold))using(var br=new SolidBrush(Color.FromArgb(218,202,164)))g.DrawString("INVENTORY  /  SAMPLE",f,br,25,25);using(var f=new Font("Arial",10))using(var br=new SolidBrush(Color.FromArgb(140,153,169)))g.DrawString("Synthetic sample - drag slots and adjust the grid",f,br,30,715);g.FillRectangle(Brushes.SlateGray,740,0,80,80);g.FillRectangle(Brushes.DarkSlateGray,740,90,80,80);g.DrawRectangle(Pens.BurlyWood,741,1,77,77);image.Save(Path.Combine(tex,"sample_atlas.png"),ImageFormat.Png);}
            Write(Path.Combine(folder,"config/ui/textures.xml"),"<w>\n <file name=\"ui\\sample_atlas\">\n  <texture id=\"sample_background\" x=\"0\" y=\"0\" width=\"720\" height=\"768\"/>\n  <texture id=\"sample_slot\" x=\"740\" y=\"0\" width=\"80\" height=\"80\"/>\n  <texture id=\"sample_belt\" x=\"740\" y=\"90\" width=\"80\" height=\"80\"/>\n </file>\n</w>");
            string ui="<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<!-- Synthetic UI: free to edit -->\n<window>\n <main x=\"0\" y=\"0\" width=\"1024\" height=\"768\"/>\n <background x=\"0\" y=\"0\" width=\"720\" height=\"768\"><texture>sample_background</texture></background>\n <dragdrop_pistol x=\"42\" y=\"100\" width=\"80\" height=\"240\" cell_width=\"80\" cell_height=\"80\" cols_num=\"1\" rows_num=\"3\"><texture>sample_slot</texture></dragdrop_pistol>\n <dragdrop_automatic x=\"142\" y=\"100\" width=\"80\" height=\"240\" cell_width=\"80\" cell_height=\"80\" cols_num=\"1\" rows_num=\"3\"><texture>sample_slot</texture></dragdrop_automatic>\n <dragdrop_belt x=\"280\" y=\"95\" width=\"400\" height=\"80\" cell_width=\"80\" cell_height=\"80\" cols_num=\"5\" rows_num=\"1\"><texture>sample_belt</texture></dragdrop_belt>\n <bag_static x=\"280\" y=\"195\" width=\"400\" height=\"440\"/>\n <dragdrop_bag x=\"0\" y=\"0\" width=\"400\" height=\"440\" cell_width=\"40\" cell_height=\"40\" cols_num=\"10\" rows_num=\"11\"/>\n</window>\n";Write(Path.Combine(folder,"config/ui/inventory_new.xml"),ui);return Path.Combine(folder,"config/ui/inventory_new.xml");}
        public static int Run(string folder){Directory.CreateDirectory(folder);var log=new StringBuilder();int count=0;try{
            string path=Path.Combine(folder,"test.xml");string original="<?xml version='1.0' encoding='windows-1251'?>\r\n<!-- Пример -->\r\n<window>\r\n#include \"other.xml\"\r\n<main x=299 y=0 width=725 height=768/>\r\n<bag_static x='20' y='40' width='100' height='100'/>\r\n<dragdrop_bag x=5 y=7 width=80 height=80 cell_width=40 cell_height=40 cols_num=2 rows_num=2/>\r\n</window>";
            File.WriteAllBytes(path,Encoding.GetEncoding(1251).GetBytes(original));var d=UiDocument.Load(path);Check(Equal(d.Bytes(),File.ReadAllBytes(path)),"CP1251 roundtrip");count++;var n=d.Xml.Root.Child("dragdrop_bag");var r=UiLayout.Rect(d,n);Check(r.X==324&&r.Y==47,"engine parent positions");count++;
            d.SetAttribute(n.Key,"x","12.5");Check(d.Text==original.Replace("<dragdrop_bag x=5","<dragdrop_bag x=12.5"),"lossless attribute patch");d.Commit(original);d.Undo();Check(d.Text==original,"undo");d.Redo();Check(d.Text.Contains("x=12.5"),"redo");count+=3;string backup=d.Save(path);Check(File.Exists(backup)&&Equal(File.ReadAllBytes(backup),Encoding.GetEncoding(1251).GetBytes(original)),"backup");Check(d.Save(path)=="","no-op save");count+=2;File.AppendAllText(path,"\n<!-- external -->");bool conflict=false;try{d.Save(path);}catch(IOException){conflict=true;}Check(conflict,"external change guard");count++;
            var fragments=new LosslessXml("<!--fragment--><button x=1/><button x='2'/>\n#include \"x.xml\"\n<text>Имя</text>");Check(fragments.Root.Name=="#fragment"&&fragments.Root.Children.Count==3,"multiple roots");Check(fragments.Root.Children[0].Key!=fragments.Root.Children[1].Key,"unique node keys");count+=2;bool invalid=false;try{new LosslessXml("<w><x></w>");}catch(FormatException){invalid=true;}Check(invalid,"reject malformed nesting");Check(new LosslessXml("").Root.Name=="#fragment","empty XML");count+=2;
            foreach(string type in new[]{"DXT1","DXT3","DXT5","A8"}){using(var b=TextureLoader.Decode(Dds(type))){Color c=b.GetPixel(0,0);Check(c.R==255&&(type=="A8"||c.G==0),type+" RGB");Check(c.A==(type=="A8"?0:type=="DXT3"?136:type=="DXT5"?200:255),type+" alpha");if(type=="A8")Check(b.GetPixel(3,3).A==255,"A8 range");}count++;}
            byte[] truncated=Dds("DXT5");Array.Resize(ref truncated,140);invalid=false;try{using(var b=TextureLoader.Decode(truncated)){} }catch(InvalidDataException){invalid=true;}Check(invalid,"reject truncated DDS");count++;
            string variants=Path.Combine(folder,"variants-"+Guid.NewGuid().ToString("N"));foreach(string v in new[]{"ui1","ui2"}){Write(Path.Combine(variants,"config/"+v+"/atlas.xml"),"<w><file name=\"ui\\same\"><texture id=\"same_id\" x=\"0\" y=\"0\" width=\"4\" height=\"4\"/></file></w>");string p=Path.Combine(variants,"textures/"+v+"/same.dds");Directory.CreateDirectory(Path.GetDirectoryName(p));File.WriteAllBytes(p,Dds(v=="ui1"?"DXT1":"DXT3"));}using(var w=new Workspace(variants)){var doc=w.Open(Path.Combine(variants,"config/ui2/atlas.xml"));w.Activate(doc);Check(doc.Atlas&&w.Resolve("same_id").FilePath.Replace('\\','/').Contains("textures/ui2"),"variant texture isolation");Check(w.Resolve("same_id").OwnerFile.Replace('\\','/').Contains("config/ui2"),"variant descriptor isolation");count+=2;}
            Check(LosslessXml.Decode("&#x41; &#1041; &amp;#65;")=="A Б &#65;","numeric XML entities decoded once");count++;
            var resized=EditorCanvas.ResizeRectangle(new RectangleF(40,50,80,90),-200,-200,4,false,16,16);Check(resized.X==40&&resized.Y==50&&resized.Width==1&&resized.Height==1,"resize cannot move stationary top-left");resized=EditorCanvas.ResizeRectangle(new RectangleF(40,50,80,90),200,200,0,false,16,16);Check(resized.Right==120&&resized.Bottom==140&&resized.Width==1&&resized.Height==1,"resize cannot move stationary bottom-right");count+=2;
            using(var input=new Bitmap(2,2))using(var output=new Bitmap(2,2)){using(var g=Graphics.FromImage(input))g.Clear(Color.FromArgb(255,200,100,50));var tx=new LosslessXml("<texture r='128' g='255' b='0' a='128'/>").Root;using(var attrs=EditorCanvas.TextureAttributes(tx))using(var g=Graphics.FromImage(output))g.DrawImage(input,new Rectangle(0,0,2,2),0,0,2,2,GraphicsUnit.Pixel,attrs);var c=output.GetPixel(0,0);Check(Math.Abs(c.R-100)<=2&&Math.Abs(c.G-100)<=2&&c.B==0&&Math.Abs(c.A-128)<=1,"RGBA preview tint");count++;}
            using(var w=new Workspace(variants)){var doc=w.Open(Path.Combine(variants,"config/ui2/atlas.xml"));w.Activate(doc);string image=Path.Combine(variants,"textures/ui2/same.dds");Check(w.Image(image).GetPixel(0,0).A==136,"initial cached DDS");File.WriteAllBytes(image,Dds("DXT5"));Check(w.Image(image).GetPixel(0,0).A==136,"cache stable until explicit refresh");Check(w.ResolveFile("ui\\late")==null,"cache missing DDS");File.WriteAllBytes(Path.Combine(variants,"textures/ui2/late.dds"),Dds("DXT1"));w.ReloadTextures();Check(w.Image(image).GetPixel(0,0).A==200&&w.ResolveFile("ui\\late")!=null,"refresh replaced DDS and missing paths");count+=4;
                string old=doc.Text;doc.SetText(doc.Text.Replace("</file>","<texture id='button_e' x='0' y='0' width='2' height='2'/><texture id='button_h' x='2' y='0' width='2' height='2'/></file>"));w.Reindex();Check(w.ResolveState("button","h").Source.X==2&&w.ResolveState("button_e","h").Id=="button_h"&&w.ResolveState("button","d").Id=="button_e","button state resolution and fallback");doc.SetText(old);count++;}
            foreach(string id in ThemeCatalog.Ids){var theme=ThemeCatalog.Create(id);Check(theme.Id==id&&theme.Name.Length>0&&theme.Text.ToArgb()!=theme.Panel.ToArgb(),"theme palette "+id);}count+=ThemeCatalog.Ids.Length;
            string brokenPath=Path.Combine(folder,"broken.xml");Write(brokenPath,"<_window><list x=1/></window>");var broken=UiDocument.Load(brokenPath);Check(broken.ParseError!=null,"invalid XML opens as source");string brokenText=broken.Text;broken.SetText(broken.Text.Replace("<_window>","<window>"));broken.Commit(brokenText);broken.Undo();Check(broken.ParseError!=null&&broken.Text==brokenText,"undo repaired XML");broken.Redo();Check(broken.ParseError==null,"redo repaired XML");count+=3;
            string example=Path.Combine(folder,"example");MakeExample(example);using(var w=new Workspace(example)){var doc=w.Open(Path.Combine(example,"config/ui/inventory_new.xml"));w.Activate(doc);Check(w.Resolve("sample_slot")!=null,"resolve example");Check(UiLayout.Validate(doc,w).Count==0,"validate example");count+=2;}
            count+=WorkflowChecks.Core(folder);log.AppendLine("PASS: "+count+" checks. Runtime "+Environment.Version+" / "+Environment.OSVersion);File.WriteAllText(Path.Combine(folder,"self-test.txt"),log.ToString());Console.WriteLine(log);return 0;
        }catch(Exception ex){log.AppendLine("FAIL after "+count+": "+ex);File.WriteAllText(Path.Combine(folder,"self-test.txt"),log.ToString());Console.Error.WriteLine(log);return 1;}}
        static void Mouse(EditorCanvas c,string method,System.Windows.Forms.MouseEventArgs e){typeof(EditorCanvas).GetMethod(method,System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic).Invoke(c,new object[]{e});}
        public static string ExerciseUI(MainForm form){var c=form.Canvas;var d=form.Document;if(d==null||d.Atlas)return "GUI: opened";UiNode n=null;foreach(var item in d.Xml.Nodes)if(item.Name=="dragdrop_pistol"){n=item;break;}if(n==null)return "GUI: opened and rendered";Action undo=delegate{typeof(MainForm).GetMethod("Undo",System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic).Invoke(form,null);};Action redo=delegate{typeof(MainForm).GetMethod("Redo",System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic).Invoke(form,null);};string original=d.Text;string key=n.Key;bool snap=c.Options.Snap;c.Options.Snap=false;c.SelectKey(key,false);c.Fit();System.Windows.Forms.Application.DoEvents();
            var r=c.ScreenRect(UiLayout.Rect(d,n));var a=new Point((int)(r.Left+r.Width/2),(int)(r.Top+r.Height/2));var b=new Point(a.X+35,a.Y+19);Mouse(c,"OnMouseDown",new System.Windows.Forms.MouseEventArgs(System.Windows.Forms.MouseButtons.Left,1,a.X,a.Y,0));Mouse(c,"OnMouseMove",new System.Windows.Forms.MouseEventArgs(System.Windows.Forms.MouseButtons.Left,0,b.X,b.Y,0));Mouse(c,"OnMouseUp",new System.Windows.Forms.MouseEventArgs(System.Windows.Forms.MouseButtons.Left,1,b.X,b.Y,0));Check(d.Text!=original,"GUI drag updates XML");undo();Check(d.Text==original,"GUI drag undo");redo();Check(d.Text!=original,"GUI drag redo");undo();
            c.SelectKey(key,false);n=d.Node(key);r=c.ScreenRect(UiLayout.Rect(d,n));a=new Point((int)r.Right,(int)r.Bottom);b=new Point(a.X+17,a.Y+23);Mouse(c,"OnMouseDown",new System.Windows.Forms.MouseEventArgs(System.Windows.Forms.MouseButtons.Left,1,a.X,a.Y,0));Mouse(c,"OnMouseMove",new System.Windows.Forms.MouseEventArgs(System.Windows.Forms.MouseButtons.Left,0,b.X,b.Y,0));Mouse(c,"OnMouseUp",new System.Windows.Forms.MouseEventArgs(System.Windows.Forms.MouseButtons.Left,1,b.X,b.Y,0));Check(d.Node(key).Number("width",0)>n.Number("width",0),"GUI resize updates width");undo();Check(d.Text==original,"GUI resize undo");
            var parent=d.Xml.Root.Child("bag_static");var child=d.Xml.Root.Child("dragdrop_bag");if(parent!=null&&child!=null){float before=UiLayout.Rect(d,child).X,local=child.Number("x",0);c.SelectKey(parent.Key,false);c.SelectKey(child.Key,true);c.MoveSelected(10,0);Check(d.Node(child.Key).Number("x",0)==local&&UiLayout.Rect(d,d.Node(child.Key)).X==before+10,"GUI group moves nested child once");undo();}
            var texture=form.Workspace.Resolve(UiLayout.TextureName(d,d.Node(key)));if(texture!=null&&texture.OwnerFile!=null){form.OpenDocument(texture.OwnerFile);c.SelectKey(texture.NodeKey,false);string atlasOriginal=form.Document.Text;float u=c.Primary.Number("x",0);c.MoveSelected(5,7);Check(form.Workspace.Resolve(texture.Id).Source.X==u+5,"GUI atlas edit refreshes aliases");undo();Check(form.Document.Text==atlasOriginal&&form.Workspace.Resolve(texture.Id).Source.X==u,"GUI atlas undo refreshes alias");form.OpenDocument(d.FilePath);}
            c.Options.BoxMode=true;c.Selection.Clear();c.Fit();System.Windows.Forms.Application.DoEvents();var left=c.ToScreen(new PointF(30,90));var right=c.ToScreen(new PointF(232,350));Mouse(c,"OnMouseDown",new System.Windows.Forms.MouseEventArgs(System.Windows.Forms.MouseButtons.Left,1,(int)left.X,(int)left.Y,0));Mouse(c,"OnMouseMove",new System.Windows.Forms.MouseEventArgs(System.Windows.Forms.MouseButtons.Left,0,(int)right.X,(int)right.Y,0));Mouse(c,"OnMouseUp",new System.Windows.Forms.MouseEventArgs(System.Windows.Forms.MouseButtons.Left,1,(int)right.X,(int)right.Y,0));Check(c.Selection.Count==2,"GUI marquee selects contained slots");c.Options.BoxMode=false;
            var previous=c.EditingAllowed;c.EditingAllowed=delegate{return false;};c.MoveSelected(20,20);Check(d.Text==original,"pending XML guard blocks canvas edits");c.EditingAllowed=previous;
            var settings=new System.Xml.XmlDocument();settings.LoadXml("<view/>");var saveView=typeof(MainForm).GetMethod("WriteView",System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic);var readView=typeof(MainForm).GetMethod("ReadView",System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic);foreach(string id in ThemeCatalog.Ids){form.SetTheme(id,false);Check(form.ThemeId==id&&d.Text==original,"GUI theme changes no game XML");saveView.Invoke(form,new object[]{settings.DocumentElement});form.SetTheme(id=="dark"?"light":"dark",false);readView.Invoke(form,new object[]{settings.DocumentElement});Check(form.ThemeId==id,"GUI theme persists "+id);}form.SetTheme("classic",false);
            WorkflowChecks.UI(form);Check(d.Text==original,"GUI preserves original after checks");c.Options.Snap=snap;c.SelectKey(key,false);return "PASS: GUI drag, resize, group parenting, marquee, pending XML guard, atlas edit, undo/redo seven persisted themes, navigation, source search/history, tree state, distribution and context menu";
        }
        public static int ValidateFolder(string root,string report){int xml=0,dds=0,edits=0,fail=0,sourceOnly=0;var log=new StringBuilder();foreach(string f in Directory.GetFiles(root,"*.xml",SearchOption.AllDirectories)){try{var d=UiDocument.Load(f);Check(Equal(File.ReadAllBytes(f),d.Bytes()),"roundtrip bytes");xml++;if(d.ParseError!=null){sourceOnly++;log.AppendLine("SOURCE ONLY "+f+": "+d.ParseError);}foreach(var n in d.Xml.Nodes){if(!n.Has("x"))continue;string old=d.Text;d.SetAttribute(n.Key,"x",UiDocument.Num(n.Number("x",0)+1));d.Commit(old);d.Undo();Check(Equal(File.ReadAllBytes(f),d.Bytes()),"edit/undo bytes");edits++;break;}}catch(Exception ex){fail++;log.AppendLine("XML "+f+": "+ex.Message);}}
            foreach(string f in Directory.GetFiles(root,"*.dds",SearchOption.AllDirectories)){try{using(var b=TextureLoader.Load(f)){Check(b.Width>0,"empty DDS");}dds++;}catch(Exception ex){fail++;log.AppendLine("DDS "+f+": "+ex.Message);}}
            log.Insert(0,"XML: "+xml+"; edit/undo: "+edits+"; DDS: "+dds+"; source-only XML: "+sourceOnly+"; failures: "+fail+Environment.NewLine);File.WriteAllText(report,log.ToString());Console.WriteLine(log.ToString().Split('\n')[0]);return fail==0?0:1;
        }
    }
}
