using System;using System.Collections.Generic;using System.Drawing;using System.IO;using System.Reflection;using System.Windows.Forms;using System.Xml;
namespace HalkUIEditor {
    public sealed partial class MainForm {
        ThemePalette currentTheme=ThemeCatalog.Create("classic");
        Color PanelColor{get{return currentTheme.Panel;}}Color InputColor{get{return currentTheme.Input;}}Color TextColor{get{return currentTheme.Text;}}Color Accent{get{return currentTheme.Accent;}}
        SplitContainer fileSplit,inspectorSplit;ThemeTabs inspectorTabs=new ThemeTabs();Label documentHeading=new Label(),documentPath=new Label(),selectedTextureLabel=new Label();Panel documentHeader;
        Dictionary<string,NumericUpDown> geometryInputs=new Dictionary<string,NumericUpDown>();Dictionary<string,ToolStripMenuItem> themeItems=new Dictionary<string,ToolStripMenuItem>();ToolStripMenuItem themeMenu;
        ComboBox textureState=new ComboBox();CheckBox previewCrop=new CheckBox();bool themeLoading,settingsLoading;string themeId="classic";int savedLeft=220,savedRight=300;
        public string ThemeId{get{return themeId;}}public ThemePalette ActivePalette{get{return currentTheme;}}
        Control CreateWorkspaceSplit(){fileSplit=new SplitContainer{Dock=DockStyle.Fill,Size=new Size(1300,700),SplitterWidth=6,Panel1MinSize=160,Panel2MinSize=560,FixedPanel=FixedPanel.Panel1,SplitterDistance=220};inspectorSplit=new SplitContainer{Dock=DockStyle.Fill,Size=new Size(1060,700),SplitterWidth=6,Panel1MinSize=260,Panel2MinSize=264,FixedPanel=FixedPanel.Panel2,SplitterDistance=754};fileSplit.Panel2.Controls.Add(inspectorSplit);return fileSplit;}
        void AttachWorkspacePanels(Control layout,Control inspector){fileSplit.Panel1.Controls.Add(leftTabs);inspectorSplit.Panel1.Controls.Add(centerTabs);inspectorSplit.Panel2.Controls.Add(inspector);}
        void InitializeEnhancements(){
            var resource=Assembly.GetExecutingAssembly().GetManifestResourceStream("HalkUIEditor.app.ico");if(resource!=null)using(resource)using(var icon=new Icon(resource))Icon=(Icon)icon.Clone();
            themeMenu=new ToolStripMenuItem("Тема: Текущая"){Alignment=ToolStripItemAlignment.Right};foreach(string id in ThemeCatalog.Ids){string choice=id;var p=ThemeCatalog.Create(id);var item=new ToolStripMenuItem(p.Name){ToolTipText=p.Detail};item.Click+=delegate{SetTheme(choice,true);};themeItems[id]=item;themeMenu.DropDownItems.Add(item);}MainMenuStrip.Items.Add(themeMenu);
            var view=MainMenuStrip.Items[2] as ToolStripMenuItem;if(view!=null){view.DropDownItems.Add(new ToolStripSeparator());AddMenu(view,"Только холст / все панели",Keys.F11,TogglePanels);AddMenu(view,"Сбросить размеры панелей",Keys.None,ResetPaneSizes);}
            var toolsMenu=MainMenuStrip.Items[3] as ToolStripMenuItem;if(toolsMenu!=null){AddMenu(toolsMenu,"Перечитать текстуры с диска",Keys.F5,ReloadTextures);AddMenu(toolsMenu,"Где используется текстура…",Keys.None,FindTextureUsages);}
            documentHeader=new Panel{Dock=DockStyle.Top,Height=55,Padding=new Padding(54,6,8,6)};documentHeading.Dock=DockStyle.Top;documentHeading.Height=23;documentHeading.Font=new Font(Font.FontFamily,10.5f,FontStyle.Bold);documentHeading.AutoEllipsis=true;documentHeading.Tag="heading";documentPath.Dock=DockStyle.Fill;documentPath.AutoEllipsis=true;documentPath.Tag="muted";documentHeader.Controls.Add(documentPath);documentHeader.Controls.Add(documentHeading);centerTabs.TabPages[0].Controls.Add(documentHeader);var emblem=new PictureBox{Size=new Size(32,32),Location=new Point(10,10),SizeMode=PictureBoxSizeMode.Zoom,Image=LoadBadge(),BackColor=Color.Transparent};documentHeader.Controls.Add(emblem);documentHeader.Paint+=delegate(object sender,PaintEventArgs e){if(themeId=="soc"||themeId=="cs"||themeId=="cop")using(var pen=new Pen(Color.FromArgb(13,Accent)))for(int y=1;y<documentHeader.Height;y+=4)e.Graphics.DrawLine(pen,0,y,documentHeader.Width,y);using(var br=new SolidBrush(Accent))e.Graphics.FillRectangle(br,0,10,3,35);};
            Canvas.EditingAllowed=delegate{return !sourceDirty;};Canvas.GeometryPreview+=delegate{UpdateGeometryInputs();};
            ConfigureCombo(parentChoice);ConfigureCombo(textureState);ConfigureCombo(aspect.ComboBox);tree.DrawMode=TreeViewDrawMode.OwnerDrawAll;tree.ShowLines=false;tree.Indent=17;tree.ItemHeight=26;tree.DrawNode+=DrawTreeNode;
            files.DrawMode=DrawMode.OwnerDrawFixed;files.ItemHeight=40;files.DrawItem+=DrawFileItem;textures.DrawMode=DrawMode.OwnerDrawFixed;textures.ItemHeight=27;textures.DrawItem+=DrawTextureItem;
            source.SelectionChanged+=delegate{if(centerTabs.SelectedIndex==1){int line=source.GetLineFromCharIndex(source.SelectionStart)+1;status.Text="XML · строка "+line+" · Ctrl+Enter применить изменения";}};
            Shown+=delegate{RestorePaneSizes();};Microsoft.Win32.SystemEvents.UserPreferenceChanged+=SystemPreferencesChanged;FormClosed+=delegate{Microsoft.Win32.SystemEvents.UserPreferenceChanged-=SystemPreferencesChanged;};SetTheme("classic",false);
        }
        void SystemPreferencesChanged(object sender,Microsoft.Win32.UserPreferenceChangedEventArgs e){if(themeId=="system"&&!IsDisposed&&IsHandleCreated)try{BeginInvoke((MethodInvoker)delegate{if(!IsDisposed&&themeId=="system")SetTheme("system",false);});}catch(InvalidOperationException){}}
        public void SetTheme(string id,bool persist){if(themeLoading)return;themeLoading=true;try{currentTheme=ThemeCatalog.Create(id);themeId=currentTheme.Id;ThemeCatalog.Apply(this,currentTheme);BackColor=currentTheme.Background;Canvas.Options.BackgroundColor=currentTheme.Canvas;Canvas.Options.GridColor=currentTheme.Grid;Canvas.Palette=currentTheme;preview.Palette=currentTheme;selectionLabel.ForeColor=Accent;projectLabel.ForeColor=Accent;documentHeading.ForeColor=Accent;documentPath.ForeColor=currentTheme.Muted;documentHeading.BackColor=Color.Transparent;documentPath.BackColor=Color.Transparent;pathLabel.ForeColor=currentTheme.Muted;textureInfo.ForeColor=currentTheme.Muted;selectedTextureLabel.ForeColor=currentTheme.Geometry;documentStatus.ForeColor=Accent;if(themeMenu!=null){themeMenu.Text="Тема: "+currentTheme.Name;foreach(var entry in themeItems)entry.Value.Checked=entry.Key==themeId;}if(Document!=null)FillTree();UpdateWorkflowState();Invalidate(true);if(persist&&!settingsLoading)SaveSettings();}finally{themeLoading=false;}}
        static Bitmap LoadBadge(){using(var stream=Assembly.GetExecutingAssembly().GetManifestResourceStream("HalkUIEditor.badge.png")){if(stream==null)return null;using(var image=Image.FromStream(stream))return new Bitmap(image);}}
        void ConfigureCombo(ComboBox combo){combo.FlatStyle=FlatStyle.Flat;combo.DrawMode=DrawMode.OwnerDrawFixed;combo.DrawItem+=delegate(object sender,DrawItemEventArgs e){bool selected=(e.State&DrawItemState.Selected)!=0&&(e.State&DrawItemState.ComboBoxEdit)==0;using(var br=new SolidBrush(selected?currentTheme.Selection:currentTheme.Input))e.Graphics.FillRectangle(br,e.Bounds);string text=e.Index>=0&&e.Index<combo.Items.Count?Convert.ToString(combo.Items[e.Index]):combo.Text;TextRenderer.DrawText(e.Graphics,text,combo.Font,new Rectangle(e.Bounds.X+5,e.Bounds.Y,Math.Max(0,e.Bounds.Width-8),e.Bounds.Height),selected?ThemeCatalog.SelectionText(currentTheme):currentTheme.Text,TextFormatFlags.VerticalCenter|TextFormatFlags.EndEllipsis|TextFormatFlags.NoPrefix);};}
        void DrawTreeNode(object sender,DrawTreeNodeEventArgs e){var p=currentTheme;bool selected=tree.SelectedNode==e.Node;var r=new Rectangle(0,e.Bounds.Y,tree.ClientSize.Width,tree.ItemHeight);using(var br=new SolidBrush(selected?p.Selection:p.Input))e.Graphics.FillRectangle(br,r);int x=20+e.Node.Level*tree.Indent;if(e.Node.Nodes.Count>0){int gx=x-12,y=e.Bounds.Y+tree.ItemHeight/2;Point[] points=e.Node.IsExpanded?new[]{new Point(gx-4,y-2),new Point(gx,y+2),new Point(gx+4,y-2)}:new[]{new Point(gx-2,y-4),new Point(gx+2,y),new Point(gx-2,y+4)};using(var pen=new Pen(selected?ThemeCatalog.SelectionText(p):p.Muted,1.4f))e.Graphics.DrawLines(pen,points);}string key=e.Node.Tag as string;var n=Document==null?null:Document.Node(key);Color color=n!=null&&Document.Hidden.Contains(key)?p.Muted:n!=null&&n.Name.StartsWith("dragdrop_")?p.Accent:n!=null&&n.Geometry?p.Geometry:p.Text;if(selected)color=ThemeCatalog.SelectionText(p);TextRenderer.DrawText(e.Graphics,e.Node.Text,tree.Font,new Rectangle(x,e.Bounds.Y,Math.Max(0,r.Width-x-5),r.Height),color,TextFormatFlags.VerticalCenter|TextFormatFlags.EndEllipsis|TextFormatFlags.NoPrefix);}
        void DrawFileItem(object sender,DrawItemEventArgs e){if(e.Index<0||e.Index>=files.Items.Count)return;var entry=files.Items[e.Index] as FileEntry;if(entry==null)return;var p=currentTheme;bool selected=(e.State&DrawItemState.Selected)!=0;using(var br=new SolidBrush(selected?p.Selection:p.Input))e.Graphics.FillRectangle(br,e.Bounds);Color main=selected?ThemeCatalog.SelectionText(p):p.Text;var title=Path.GetFileName(entry.Path);if(entry.Label.StartsWith("* "))title="● "+title;TextRenderer.DrawText(e.Graphics,title,files.Font,new Rectangle(e.Bounds.X+10,e.Bounds.Y+3,e.Bounds.Width-16,20),main,TextFormatFlags.EndEllipsis|TextFormatFlags.NoPrefix);string dir=Path.GetDirectoryName(entry.Label.Replace("* ",""));TextRenderer.DrawText(e.Graphics,dir,files.Font,new Rectangle(e.Bounds.X+10,e.Bounds.Y+22,e.Bounds.Width-16,16),selected?main:p.Muted,TextFormatFlags.EndEllipsis|TextFormatFlags.NoPrefix);}
        void DrawTextureItem(object sender,DrawItemEventArgs e){if(e.Index<0||e.Index>=textures.Items.Count)return;var p=currentTheme;bool selected=(e.State&DrawItemState.Selected)!=0;using(var br=new SolidBrush(selected?p.Selection:p.Input))e.Graphics.FillRectangle(br,e.Bounds);using(var pen=new Pen(p.Geometry))e.Graphics.DrawRectangle(pen,e.Bounds.X+8,e.Bounds.Y+8,10,10);TextRenderer.DrawText(e.Graphics,textures.Items[e.Index].ToString(),textures.Font,new Rectangle(e.Bounds.X+25,e.Bounds.Y,e.Bounds.Width-30,e.Bounds.Height),selected?ThemeCatalog.SelectionText(p):p.Text,TextFormatFlags.VerticalCenter|TextFormatFlags.EndEllipsis|TextFormatFlags.NoPrefix);}
        Control CreateInspectorTabs(){var host=new Panel{Dock=DockStyle.Fill,Padding=new Padding(8,7,8,4)};var head=new TableLayoutPanel{Dock=DockStyle.Top,ColumnCount=1,RowCount=0,Height=112};head.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));selectionLabel.Font=new Font(Font.FontFamily,10.5f,FontStyle.Bold);selectionLabel.AutoEllipsis=true;selectionLabel.Tag="heading";AddRow(head,selectionLabel,26);coordsLabel.Tag="muted";AddRow(head,coordsLabel,36);pathLabel.AutoEllipsis=true;pathLabel.Tag="muted";AddRow(head,pathLabel,23);selectedTextureLabel.AutoEllipsis=true;selectedTextureLabel.Cursor=Cursors.Hand;selectedTextureLabel.Click+=delegate{inspectorTabs.SelectedIndex=1;};AddRow(head,selectedTextureLabel,25);
            inspectorTabs.Dock=DockStyle.Fill;inspectorTabs.ItemSize=new Size(86,30);var geometry=new TabPage("Геометрия");var texture=new TabPage("Текстура");var attributes=new TabPage("Атрибуты");StylePage(geometry);StylePage(texture);StylePage(attributes);inspectorTabs.TabPages.AddRange(new[]{geometry,texture,attributes});host.Controls.Add(inspectorTabs);host.Controls.Add(head);
            var content=new Panel{Dock=DockStyle.Fill,AutoScroll=true,Padding=new Padding(3,9,3,4)};geometry.Controls.Add(content);var stack=new TableLayoutPanel{Dock=DockStyle.Top,AutoSize=true,ColumnCount=1,RowCount=0};stack.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));content.Controls.Add(stack);
            var inputs=new TableLayoutPanel{ColumnCount=2,RowCount=2,Padding=new Padding(0)};inputs.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,50));inputs.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,50));inputs.RowStyles.Add(new RowStyle(SizeType.Percent,50));inputs.RowStyles.Add(new RowStyle(SizeType.Percent,50));int idx=0;foreach(string name in new[]{"x","y","width","height"}){string key=name;var cell=new Panel{Dock=DockStyle.Fill,Padding=new Padding(2,0,5,4)};var label=LabelFor(name=="width"?"ШИРИНА W":name=="height"?"ВЫСОТА H":name=="x"?"ПОЗИЦИЯ X":"ПОЗИЦИЯ Y");label.Dock=DockStyle.Top;label.Height=20;var input=new NumericUpDown{Dock=DockStyle.Bottom,Minimum=name=="x"||name=="y"?-1000000:0,Maximum=1000000,DecimalPlaces=3,Increment=1,ThousandsSeparator=false,Height=25};geometryInputs[key]=input;input.ValueChanged+=delegate{if(binding||Canvas.Primary==null)return;string node=Canvas.Primary.Key;string value=UiDocument.Num((float)input.Value);Guard(delegate{Change(delegate{Document.SetAttribute(node,key,value);});});};cell.Controls.Add(input);cell.Controls.Add(label);inputs.Controls.Add(cell,idx%2,idx/2);idx++;}AddRow(stack,inputs,116);
            AddRow(stack,SmallButton("Размер контейнера по ячейкам",SyncGrid),33);AddRow(stack,LabelFor("ПОЛОЖЕНИЕ ГРУППЫ"),27);var alignment=new FlowLayoutPanel{WrapContents=false};alignment.Controls.Add(SmallButton("Слева",delegate{Canvas.Align("left");}));alignment.Controls.Add(SmallButton("Сверху",delegate{Canvas.Align("top");}));alignment.Controls.Add(SmallButton("Центры X",delegate{Canvas.Align("centerx");}));AddRow(stack,alignment,34);
            AddRow(stack,LabelFor("РОДИТЕЛЬ ДЛЯ ПРОСМОТРА"),28);parentChoice.DropDownStyle=ComboBoxStyle.DropDownList;parentChoice.DropDownWidth=550;StyleInput(parentChoice);AddRow(stack,parentChoice,28);engine.Text="Правила инвентаря X-Ray";engine.Checked=true;AddRow(stack,engine,28);tips.SetToolTip(engine,"Связи main, bag_static и индикаторов. Настройки родителей влияют на просмотр, а не на XML игры.");var flags=new FlowLayoutPanel{WrapContents=false};hidden.Text="Скрыть";hidden.Width=85;locked.Text="Блокировать";locked.Width=145;flags.Controls.Add(hidden);flags.Controls.Add(locked);AddRow(stack,flags,30);tips.SetToolTip(locked,"Запрещает перемещение и изменение размера на холсте.");var operations=new FlowLayoutPanel{WrapContents=false};operations.Controls.Add(SmallButton("Дубликат",Duplicate));operations.Controls.Add(SmallButton("Удалить",Delete));AddRow(stack,operations,34);AddRow(stack,SmallButton("Показать выбранный тег в XML",ShowInSource),32);
            var texStack=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=1,RowCount=0,Padding=new Padding(3,8,3,4)};texStack.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));texture.Controls.Add(texStack);AddRow(texStack,LabelFor("TEXTURE ID / ФАЙЛ АТЛАСА"),23);StyleInput(textureName);AddRow(texStack,textureName,28);AddRow(texStack,SmallButton("Применить имя текстуры",ApplyTextureText),33);textureState.DropDownStyle=ComboBoxStyle.DropDownList;textureState.Items.AddRange(new object[]{"Обычное · _e","Под указателем · _h","Нажатое · _t","Недоступное · _d"});textureState.SelectedIndex=0;textureState.SelectedIndexChanged+=delegate{Canvas.Options.TextureState=new[]{"e","h","t","d"}[Math.Max(0,textureState.SelectedIndex)];ShowSelection();Canvas.Invalidate();};AddRow(texStack,textureState,29);previewCrop.Text="Крупно показать выбранный фрагмент";previewCrop.Checked=true;previewCrop.CheckedChanged+=delegate{preview.Crop=previewCrop.Checked;preview.Invalidate();};AddRow(texStack,previewCrop,27);int row=texStack.RowCount++;texStack.RowStyles.Add(new RowStyle(SizeType.Percent,100));preview.Dock=DockStyle.Fill;preview.Margin=new Padding(0,5,0,7);texStack.Controls.Add(preview,0,row);textureInfo.AutoEllipsis=true;textureInfo.Tag="muted";AddRow(texStack,textureInfo,55);AddRow(texStack,SmallButton("Открыть область в атласе",JumpAtlas),32);AddRow(texStack,SmallButton("Где используется текстура",FindTextureUsages),32);
            properties.Dock=DockStyle.Fill;properties.BorderStyle=BorderStyle.None;properties.RowHeadersVisible=false;properties.AllowUserToAddRows=false;properties.AllowUserToDeleteRows=false;properties.AllowUserToResizeRows=false;properties.AutoSizeColumnsMode=DataGridViewAutoSizeColumnsMode.Fill;properties.RowTemplate.Height=27;properties.ColumnHeadersHeight=30;properties.Columns.Add("attribute","Атрибут");properties.Columns.Add("value","Значение");properties.Columns[0].ReadOnly=true;properties.Columns[0].FillWeight=47;properties.Columns[1].FillWeight=53;attributes.Controls.Add(properties);var buttons=new FlowLayoutPanel{Dock=DockStyle.Bottom,Height=37,Padding=new Padding(2,4,2,2),WrapContents=false};buttons.Controls.Add(SmallButton("+ Атрибут",AddAttribute));buttons.Controls.Add(SmallButton("− Атрибут",RemoveAttribute));attributes.Controls.Add(buttons);return host;
        }
        void UpdateGeometryInputs(){bool old=binding;binding=true;var n=Canvas.Primary;foreach(var pair in geometryInputs){var input=pair.Value;input.Enabled=n!=null&&n.Geometry;decimal value=n==null?0:(decimal)Math.Max(-1000000,Math.Min(1000000,n.Number(pair.Key,0)));input.Value=Math.Max(input.Minimum,Math.Min(input.Maximum,value));}binding=old;}
        void UpdateWorkspaceHeading(){documentHeading.Text=Document==null?"X-RAY UI EDITOR 1.2":(Document.Dirty||sourceDirty?"●  ":"")+Path.GetFileName(Document.FilePath);documentPath.Text=Document==null?"Откройте XML или папку с интерфейсом":(Document.Atlas?"АТЛАС  /  ":"РАЗВЁРСТКА  /  ")+Workspace.ActiveVariant+"  /  "+Relative(Document.FilePath);tips.SetToolTip(documentPath,Document==null?"":Document.FilePath);}
        void RestorePaneSizes(){if(fileSplit==null)return;int max=fileSplit.Width-fileSplit.Panel2MinSize-fileSplit.SplitterWidth;if(max>=fileSplit.Panel1MinSize)fileSplit.SplitterDistance=Math.Max(fileSplit.Panel1MinSize,Math.Min(max,savedLeft));max=inspectorSplit.Width-inspectorSplit.Panel2MinSize-inspectorSplit.SplitterWidth;if(max>=inspectorSplit.Panel1MinSize)inspectorSplit.SplitterDistance=Math.Max(inspectorSplit.Panel1MinSize,Math.Min(max,inspectorSplit.Width-savedRight-inspectorSplit.SplitterWidth));}
        void ResetPaneSizes(){savedLeft=220;savedRight=300;RestorePaneSizes();Canvas.Fit();}
        void TogglePanels(){bool collapse=!fileSplit.Panel1Collapsed;fileSplit.Panel1Collapsed=collapse;inspectorSplit.Panel2Collapsed=collapse;Canvas.Fit();}
        void ReloadTextures(){if(Workspace==null)return;UseWaitCursor=true;try{Workspace.ReloadTextures();FillTextures();ShowSelection();Canvas.Invalidate();status.Text="Текстуры перечитаны с диска; кэш обновлён.";}finally{UseWaitCursor=false;}}
        void FindTextureUsages(){if(Workspace==null||Canvas.Primary==null)return;string id=Document.Atlas?Canvas.Primary.Get("id",""):UiLayout.TextureName(Document,Canvas.Primary);if(id=="")return;var hits=new List<KeyEntry>();foreach(string path in Workspace.Files){if(Workspace.Variant(path)!=Workspace.ActiveVariant)continue;try{var doc=Workspace.Open(path);if(doc.Atlas)continue;foreach(var node in doc.Xml.Nodes){if(node.Children.Count==0)continue;bool found=false;foreach(string state in new[]{"e","h","t","d"})if(UiLayout.TextureName(doc,node,state)==id)found=true;if(found)hits.Add(new KeyEntry{Key=path+"\n"+node.Key,Label=Relative(path)+"  ›  "+node.Name});}}catch(Exception){}}
            using(var dialog=new Form{Text="Использование: "+id,Size=new Size(780,450),StartPosition=FormStartPosition.CenterParent,Font=Font}){var list=new ListBox{Dock=DockStyle.Fill,IntegralHeight=false,HorizontalScrollbar=true,BorderStyle=BorderStyle.None};foreach(var hit in hits)list.Items.Add(hit);var title=new Label{Dock=DockStyle.Top,Height=48,Padding=new Padding(10),Text=hits.Count==0?"Совпадений в текущем варианте UI не найдено.":"Найдено: "+hits.Count+". Двойной щелчок откроет элемент."};KeyEntry choice=null;list.DoubleClick+=delegate{choice=list.SelectedItem as KeyEntry;if(choice!=null)dialog.Close();};dialog.Controls.Add(list);dialog.Controls.Add(title);ThemeCatalog.Apply(dialog,currentTheme);dialog.ShowDialog(this);if(choice!=null){int split=choice.Key.IndexOf('\n');OpenDocument(choice.Key.Substring(0,split));Canvas.SelectKey(choice.Key.Substring(split+1),false);Canvas.FitSelection();}}}
        void SaveThemeSettings(XmlElement e){e.SetAttribute("theme",themeId);if(fileSplit!=null){e.SetAttribute("left_panel",fileSplit.SplitterDistance.ToString());e.SetAttribute("right_panel",(inspectorSplit.Width-inspectorSplit.SplitterDistance-inspectorSplit.SplitterWidth).ToString());}e.SetAttribute("preview_crop",preview.Crop?"1":"0");}
        void LoadThemeSettings(XmlElement e){settingsLoading=true;try{SetTheme(e.HasAttribute("theme")?e.GetAttribute("theme"):"classic",false);int v;if(int.TryParse(e.GetAttribute("left_panel"),out v)&&v>=160&&v<=600)savedLeft=v;if(int.TryParse(e.GetAttribute("right_panel"),out v)&&v>=264&&v<=600)savedRight=v;previewCrop.Checked=!e.HasAttribute("preview_crop")||e.GetAttribute("preview_crop")!="0";}finally{settingsLoading=false;}}
        protected override bool ProcessCmdKey(ref Message msg,Keys keyData){if(Canvas.ContainsFocus){if(keyData==Keys.Delete){Guard(Delete);return true;}if(keyData==(Keys.Control|Keys.A)){Canvas.SelectAll();return true;}}return base.ProcessCmdKey(ref msg,keyData);}
    }
}
