from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def collect_files(root: Path) -> list[Path]:
    return sorted((path for path in root.rglob("*") if path.is_file()), key=lambda path: path.as_posix().lower())


def validate(ready_root: Path) -> None:
    ready_root = ready_root.resolve()
    if not ready_root.is_dir():
        raise FileNotFoundError(f"RC6 ready directory not found: {ready_root}")

    bin_root = ready_root / "bin"
    gamedata_root = ready_root / "gamedata"
    if not bin_root.is_dir():
        raise RuntimeError(f"RC6 release is missing bin/: {bin_root}")
    if not gamedata_root.is_dir():
        raise RuntimeError(f"RC6 release is missing cumulative gamedata/: {gamedata_root}")

    bin_files = collect_files(bin_root)
    runtime_files = [path for path in bin_files if path.suffix.lower() in {".exe", ".dll"}]
    if not runtime_files:
        raise RuntimeError("RC6 release bin/ contains no EXE/DLL runtime files")

    gamedata_files = collect_files(gamedata_root)
    marker = gamedata_root / "RC6_VULKAN_BUILD.txt"
    if not marker.is_file():
        raise RuntimeError("RC6 cumulative gamedata marker is missing")

    # The marker itself is generated by the staging step.  Any integration overlay or
    # upstream gamedata resources remain in the same recursive tree and are therefore
    # covered by the release manifest below.
    payload = []
    for path in sorted(set(bin_files + gamedata_files), key=lambda item: item.as_posix().lower()):
        relative = path.relative_to(ready_root).as_posix()
        payload.append({
            "path": relative,
            "size": path.stat().st_size,
            "sha256": sha256(path),
        })

    manifest = {
        "format": 1,
        "runtime_files": len(bin_files),
        "runtime_binaries": len(runtime_files),
        "gamedata_files": len(gamedata_files),
        "files": payload,
    }
    manifest_path = ready_root / "RC6_RELEASE_MANIFEST.json"
    manifest_path.write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

    print(
        f"[release-payload] verified bin={len(bin_files)} files "
        f"({len(runtime_files)} EXE/DLL), gamedata={len(gamedata_files)} files; "
        f"manifest={manifest_path.name}"
    )


def main() -> int:
    parser = argparse.ArgumentParser(description="Validate RC6 x64 Vulkan runtime + cumulative gamedata release payload.")
    parser.add_argument("--ready", default="READY_RC6_X64_VULKAN")
    args = parser.parse_args()
    validate(Path(args.ready))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
